// The P4 base `Generator`'s dispatch mechanism, asserted against CPython's own.
//
// PORT_PLAN.md §4.3 item 2: `_gen/dispatch/` exists to ASSERT the runtime builder,
// never to replace it. These tests are that assertion. The snapshot is
// `src/_gen/dispatch/index.js`, generated by `tools/gen_dispatch.mjs` from
// `corpus/parity/dispatch.json`, which `tools/parity/extract.py` produced by calling
// upstream's own `_build_dispatch` — so the expectations are CPython's, not a
// re-derivation that could share a bug with the code under test.
//
// The end-to-end SQL differential lives in `spike/p4/fuzz_generator_base.mjs` (it needs
// a Python oracle); these are the structural invariants that must hold on every run of
// `node --test`, with no Python present.

import test from "node:test";
import assert from "node:assert/strict";
import * as exp from "../src/expressions/index.js";
import { Generator, _buildDispatch, BASE_DIALECT_GENERATOR_SETTINGS } from "../src/generator.js";
import { PyValueError } from "../src/_py/errors.js";
import { DISPATCH } from "../src/_gen/dispatch/index.js";

const WANT = DISPATCH.Generator;

test("_buildDispatch resolves every *_sql method CPython does, to the same handler", () => {
  const got = new Map([..._buildDispatch(Generator)].map(([cls, h]) => [cls.name, h]));

  // The 417 method-derived entries must match EXACTLY: same expression classes, same
  // handler names. A count-only check would pass with two names swapped.
  const wantMethod = Object.entries(WANT).filter(([, h]) => h !== "transform");
  assert.equal(wantMethod.length, 417, "snapshot should carry 417 method-derived entries");

  const mismatched = [];
  for (const [exprName, handler] of wantMethod) {
    if (got.get(exprName) !== handler) {
      mismatched.push(`${exprName}: got ${got.get(exprName)}, want ${handler}`);
    }
  }
  assert.deepEqual(mismatched, [], "every method-derived dispatch entry must match CPython");

  // And nothing EXTRA: a `*_sql` name that is not upstream's would silently claim a
  // node type. `got` may legitimately lack the 143 TRANSFORMS entries at this step,
  // but it must never contain a class CPython does not dispatch at all.
  const extra = [...got.keys()].filter((n) => !(n in WANT));
  assert.deepEqual(extra, [], "no dispatch entry may exist that CPython does not have");
});

test("the only gap versus CPython is the deliberately-unseeded TRANSFORMS", () => {
  // R13: a table of zero real entries reads as "seeded" and blocks everything behind
  // it. This test states the gap as a NUMBER so it cannot be mistaken for done, and it
  // will fail the moment TRANSFORMS starts being filled — at which point whoever fills
  // it updates the expectation deliberately rather than discovering the drift later.
  assert.equal(Generator.TRANSFORMS.size, 0, "TRANSFORMS is skeleton at the blocking step");

  const wantTransform = Object.entries(WANT).filter(([, h]) => h === "transform");
  assert.equal(wantTransform.length, 143);

  const got = _buildDispatch(Generator);
  assert.equal(got.size, Object.keys(WANT).length - wantTransform.length);
  assert.equal(got.size, 417);
});

test("TRANSFORMS beats a same-named *_sql method", () => {
  // The precedence rule is invisible in the base class (measured at the pin: 0 of the
  // 143 base TRANSFORMS keys shadow a base `*_sql`), so it is only ever exercised by a
  // dialect generator. Asserting it here means it is verified BEFORE the first dialect
  // generator depends on it, rather than discovered by that dialect being wrong.
  class Dialecty extends Generator {
    static TRANSFORMS = new Map([[exp.Star, () => "FROM_TRANSFORMS"]]);
  }
  const d = _buildDispatch(Dialecty);
  assert.equal(typeof d.get(exp.Star), "function", "a TRANSFORMS entry stays a callable");
  assert.equal(d.get(exp.Star)(), "FROM_TRANSFORMS");

  // ...and the base still routes Star to its own method, so the subclass did not
  // mutate shared state.
  assert.equal(_buildDispatch(Generator).get(exp.Star), "star_sql");

  // End-to-end through sql(), which is what actually matters.
  assert.equal(new Dialecty().sql(new exp.Star()), "FROM_TRANSFORMS");
  assert.equal(new Generator().sql(new exp.Star()), "*");
});

test("a subclass's *_sql override wins over the base method", () => {
  class Louder extends Generator {
    boolean_sql(expression) {
      return expression.this ? "YES" : "NO";
    }
  }
  assert.equal(new Louder().sql(new exp.Boolean({ this: true })), "YES");
  assert.equal(new Generator().sql(new exp.Boolean({ this: true })), "TRUE");
});

test("the dispatch cache is keyed by class, not shared across classes", () => {
  class A extends Generator {}
  class B extends Generator {}
  const a1 = new A();
  const a2 = new A();
  assert.equal(a1._dispatch, a2._dispatch, "same class shares one resolved table");
  assert.notEqual(a1._dispatch, new B()._dispatch, "different classes get their own");
});

test("sql() dispatches on EXACT class, with only the Func and Property fallbacks", () => {
  const g = new Generator();

  // Exact-class: `Null` is dispatched; a hypothetical subclass of it is NOT, and must
  // fall through rather than silently inherit `null_sql`. This is a dict lookup
  // upstream (`self._dispatch.get(expression.__class__)`), not an isinstance walk, and
  // conflating the two would change which handler runs for many dialect nodes.
  assert.equal(g.sql(new exp.Null()), "NULL");

  // Fallback 1: a Func with no `*_sql` of its own.
  assert.ok(!("abs_sql" in Generator.prototype), "Abs must have no dedicated method");
  assert.equal(g.sql(new exp.Abs({ this: exp.Literal.number(1) })), "ABS(1)");

  // Fallback 2: a bare Property. The key is UNQUOTED — `property_name(expression)`
  // defaults to `string_key=False` and returns `expression.name`, not the rendered
  // Literal. Confirmed against CPython, which emits exactly this.
  assert.equal(
    g.sql(new exp.Property({ this: exp.Literal.string("k"), value: exp.Literal.string("v") })),
    "k='v'",
  );

  // And nothing else. If this ever stops throwing, the fallbacks have widened and
  // every unported node would render as something plausible instead of failing.
  assert.throws(() => g.sql(new exp.Expr({})), /Unsupported expression type Expr/);
});

test("Expr.sql() is wired to the generator (the registerGenerator hook has a caller)", () => {
  // `expressions/core.js:515` exported `registerGenerator` from P2 and nothing called
  // it, so `.sql()` was permanently a throw — R19's shape. Importing generator.js
  // installs it; this asserts the wiring rather than the export's existence.
  assert.equal(new exp.Star().sql(), "*");
  assert.equal(exp.Literal.string("it's").sql(), "'it''s'");
  assert.equal(new exp.Abs({ this: exp.Literal.number(1) }).sql(), "ABS(1)");
});

test("too_wide counts CODE POINTS, not UTF-16 units", () => {
  // Review finding B2 / R4: a `.length` port passes all 15,642 corpus rows and is
  // still wrong, because the corpus is 0.024% non-ASCII. 27 astral characters are
  // 27 code points but 54 UTF-16 units, so `.length` would call this "too wide".
  const g = new Generator();
  const astral = "\u{1f600}".repeat(27);
  assert.equal(astral.length, 54, "precondition: JS counts these as 54 units");
  assert.equal(g.too_wide([astral]), false, "27 code points is under the 80 default");
  assert.equal(g.too_wide(["x".repeat(81)]), true);
});

test("class settings are read through this.constructor, so subclasses can override", () => {
  // Rule 1. A bare `this.STAR_EXCEPT` reads back `undefined` from an instance method
  // with no error — the failure mode that had to be swept out of src/parser.js.
  class Weird extends Generator {
    static STAR_EXCEPT = "MINUS";
  }
  const star = new exp.Star({ except_: [exp.Literal.string("a")] }, { skipInitHook: true });
  assert.equal(new Generator().sql(star), "* EXCEPT ('a')");
  assert.equal(new Weird().sql(star), "* MINUS ('a')");
});

test("a dialect NAME is refused rather than silently defaulting", () => {
  // CONTRACTS.md §8, same rule Tokenizer and Parser already enforce: falling back to
  // the default dialect would make every per-dialect generate-oracle row vacuously
  // green.
  assert.throws(() => new Generator({ dialect: "snowflake" }), /dialects\/dialect\.js is P5/);
  assert.equal(new Generator().dialect, BASE_DIALECT_GENERATOR_SETTINGS);
  assert.equal(new Generator({ dialect: null }).dialect, BASE_DIALECT_GENERATOR_SETTINGS);
});

test("SUPPORTED_JSON_PATH_PARTS announces its deferral instead of reading undefined", () => {
  // The one setting whose value lives in the unported jsonpath module. An empty Set
  // would make every membership test silently false; absence would read `undefined`
  // and surface as an output mismatch far from the cause (R18's
  // REGEXP_EXTRACT_DEFAULT_GROUP). It throws instead.
  assert.throws(() => Generator.SUPPORTED_JSON_PATH_PARTS, /not ported yet/);
});

test("property_sql renders a missed lookup as Python's 'None', not 'undefined'", () => {
  // Found by adversarial review. `PROPERTY_TO_NAME.get()` misses for several real,
  // reachable property classes; Python's f-string then renders `str(None)` = "None"
  // while a JS template literal renders "undefined". Reachable and observable:
  // StorageHandlerProperty has no PROPERTY_TO_NAME entry and no *_sql method, so it
  // lands in property_sql, one of sql()'s only two fallbacks. CPython @ 91119bc emits
  // exactly "None='x'" — verified directly, not reasoned about.
  const g = new Generator();
  const node = new exp.StorageHandlerProperty({ this: exp.Literal.string("x") });
  assert.equal(g.sql(node), "None='x'");
  assert.deepEqual(g.unsupported_messages, ["Unsupported property storagehandlerproperty"]);
});

test("sql() raises PyValueError, the port's stand-in for Python's ValueError", () => {
  // Upstream generator.py:1131 is `raise ValueError`. A JS TypeError is neither that
  // type nor a PyException, so it would be invisible to `instanceof PyValueError`.
  assert.throws(
    () => new Generator().sql(new exp.Expr({})),
    (e) => e instanceof PyValueError && /Unsupported expression type Expr/.test(e.message),
  );
});

test("a trailing enum ARGUMENT is not mistaken for an options object", () => {
  // `exp.DType.*` and `Properties.Location.*` are plain frozen objects, so the naive
  // `constructor === Object` options test swallows them and drops the argument from the
  // output with no error. Not reachable from any upstream call site today — which is
  // exactly the kind of "safe for now" that R18 records as expiring silently, with 426
  // stubs still to be written against these signatures.
  const g = new Generator();
  assert.equal(exp.DType.VARCHAR.constructor, Object, "precondition: DType is a plain object");
  // The enum must survive into format_args and be rendered (or fail loudly), never
  // vanish. Rendering an unsupported node type raises — that is the loud outcome.
  assert.throws(() => g.func("F", exp.Literal.string("a"), exp.DType.VARCHAR), PyValueError);
  // ...whereas a real options object is still consumed. `suffix` REPLACES the default
  // ")" rather than being appended to it, so this is "F('a']" — confirmed against
  // CPython, which emits the same.
  assert.equal(g.func("F", exp.Literal.string("a"), { suffix: "]" }), "F('a']");
});

test("the seeded skeleton's size is stated, not implied", () => {
  // R13's demand made executable: the burndown numbers live in a test, so a PR that
  // ports stubs updates them deliberately.
  const sqlMethods = Object.getOwnPropertyNames(Generator.prototype).filter((n) => n.endsWith("_sql"));
  assert.equal(sqlMethods.length, 432, "upstream has 432 *_sql methods (424 public + 8 private)");

  const stubs = sqlMethods.filter((n) => {
    try {
      new Generator()[n](new exp.Expr({}));
      return false;
    } catch (e) {
      return e.name === "NotPorted";
    }
  });
  assert.equal(432 - stubs.length, 6, "exactly 6 *_sql methods are wired at the blocking step");
});
