// The P4 base `Generator`'s dispatch mechanism, asserted against CPython's own.
//
// PORT_PLAN.md §4.3 item 2: `_gen/dispatch/` exists to ASSERT the runtime builder,
// never to replace it. These tests are that assertion. The snapshot is
// `src/_gen/dispatch/index.js`, generated by `tools/gen_dispatch.mjs` from
// `corpus/parity/dispatch.json`, which `tools/parity/extract.py` produced by calling
// upstream's own `_build_dispatch` — so the expectations are CPython's, not a
// re-derivation that could share a bug with the code under test.
//
// The end-to-end SQL differential lives in `spike/p4/fuzz_generator_base.mjs` (it needs
// a Python oracle); these are the structural invariants that must hold on every run of
// `node --test`, with no Python present.

import test from "node:test";
import assert from "node:assert/strict";
import * as exp from "../src/expressions/index.js";
import { Generator, _buildDispatch, BASE_DIALECT_GENERATOR_SETTINGS } from "../src/generator.js";
import { PyValueError } from "../src/_py/errors.js";
import { DISPATCH } from "../src/_gen/dispatch/index.js";

const WANT = DISPATCH.Generator;

test("_buildDispatch resolves every *_sql method CPython does, to the same handler", () => {
  const got = new Map([..._buildDispatch(Generator)].map(([cls, h]) => [cls.name, h]));

  // The 417 method-derived entries must match EXACTLY: same expression classes, same
  // handler names. A count-only check would pass with two names swapped.
  const wantMethod = Object.entries(WANT).filter(([, h]) => h !== "transform");
  assert.equal(wantMethod.length, 417, "snapshot should carry 417 method-derived entries");

  const mismatched = [];
  for (const [exprName, handler] of wantMethod) {
    if (got.get(exprName) !== handler) {
      mismatched.push(`${exprName}: got ${got.get(exprName)}, want ${handler}`);
    }
  }
  assert.deepEqual(mismatched, [], "every method-derived dispatch entry must match CPython");

  // And nothing EXTRA: a `*_sql` name that is not upstream's would silently claim a
  // node type. `got` may legitimately lack the 143 TRANSFORMS entries at this step,
  // but it must never contain a class CPython does not dispatch at all.
  const extra = [...got.keys()].filter((n) => !(n in WANT));
  assert.deepEqual(extra, [], "no dispatch entry may exist that CPython does not have");
});

test("the only gap versus CPython is the deliberately-unseeded TRANSFORMS", () => {
  // R13: a table of zero real entries reads as "seeded" and blocks everything behind
  // it. This test states the gap as a NUMBER so it cannot be mistaken for done, and it
  // will fail the moment TRANSFORMS starts being filled — at which point whoever fills
  // it updates the expectation deliberately rather than discovering the drift later.
  assert.equal(Generator.TRANSFORMS.size, 0, "TRANSFORMS is skeleton at the blocking step");

  const wantTransform = Object.entries(WANT).filter(([, h]) => h === "transform");
  assert.equal(wantTransform.length, 143);

  const got = _buildDispatch(Generator);
  assert.equal(got.size, Object.keys(WANT).length - wantTransform.length);
  assert.equal(got.size, 417);
});

test("TRANSFORMS beats a same-named *_sql method", () => {
  // The precedence rule is invisible in the base class (measured at the pin: 0 of the
  // 143 base TRANSFORMS keys shadow a base `*_sql`), so it is only ever exercised by a
  // dialect generator. Asserting it here means it is verified BEFORE the first dialect
  // generator depends on it, rather than discovered by that dialect being wrong.
  class Dialecty extends Generator {
    static TRANSFORMS = new Map([[exp.Star, () => "FROM_TRANSFORMS"]]);
  }
  const d = _buildDispatch(Dialecty);
  assert.equal(typeof d.get(exp.Star), "function", "a TRANSFORMS entry stays a callable");
  assert.equal(d.get(exp.Star)(), "FROM_TRANSFORMS");

  // ...and the base still routes Star to its own method, so the subclass did not
  // mutate shared state.
  assert.equal(_buildDispatch(Generator).get(exp.Star), "star_sql");

  // End-to-end through sql(), which is what actually matters.
  assert.equal(new Dialecty().sql(new exp.Star()), "FROM_TRANSFORMS");
  assert.equal(new Generator().sql(new exp.Star()), "*");
});

test("a subclass's *_sql override wins over the base method", () => {
  class Louder extends Generator {
    boolean_sql(expression) {
      return expression.this ? "YES" : "NO";
    }
  }
  assert.equal(new Louder().sql(new exp.Boolean({ this: true })), "YES");
  assert.equal(new Generator().sql(new exp.Boolean({ this: true })), "TRUE");
});

test("the dispatch cache is keyed by class, not shared across classes", () => {
  class A extends Generator {}
  class B extends Generator {}
  const a1 = new A();
  const a2 = new A();
  assert.equal(a1._dispatch, a2._dispatch, "same class shares one resolved table");
  assert.notEqual(a1._dispatch, new B()._dispatch, "different classes get their own");
});

test("sql() dispatches on EXACT class, with only the Func and Property fallbacks", () => {
  const g = new Generator();

  // Exact-class: `Null` is dispatched; a hypothetical subclass of it is NOT, and must
  // fall through rather than silently inherit `null_sql`. This is a dict lookup
  // upstream (`self._dispatch.get(expression.__class__)`), not an isinstance walk, and
  // conflating the two would change which handler runs for many dialect nodes.
  assert.equal(g.sql(new exp.Null()), "NULL");

  // Fallback 1: a Func with no `*_sql` of its own.
  assert.ok(!("abs_sql" in Generator.prototype), "Abs must have no dedicated method");
  assert.equal(g.sql(new exp.Abs({ this: exp.Literal.number(1) })), "ABS(1)");

  // Fallback 2: a bare Property. The key is UNQUOTED — `property_name(expression)`
  // defaults to `string_key=False` and returns `expression.name`, not the rendered
  // Literal. Confirmed against CPython, which emits exactly this.
  assert.equal(
    g.sql(new exp.Property({ this: exp.Literal.string("k"), value: exp.Literal.string("v") })),
    "k='v'",
  );

  // And nothing else. If this ever stops throwing, the fallbacks have widened and
  // every unported node would render as something plausible instead of failing.
  assert.throws(() => g.sql(new exp.Expr({})), /Unsupported expression type Expr/);
});

test("Expr.sql() is wired to the generator (the registerGenerator hook has a caller)", () => {
  // `expressions/core.js:515` exported `registerGenerator` from P2 and nothing called
  // it, so `.sql()` was permanently a throw — R19's shape. Importing generator.js
  // installs it; this asserts the wiring rather than the export's existence.
  assert.equal(new exp.Star().sql(), "*");
  assert.equal(exp.Literal.string("it's").sql(), "'it''s'");
  assert.equal(new exp.Abs({ this: exp.Literal.number(1) }).sql(), "ABS(1)");
});

test("too_wide counts CODE POINTS, not UTF-16 units", () => {
  // Review finding B2 / R4: a `.length` port passes all 15,642 corpus rows and is
  // still wrong, because the corpus is 0.024% non-ASCII. 27 astral characters are
  // 27 code points but 54 UTF-16 units, so `.length` would call this "too wide".
  const g = new Generator();
  const astral = "\u{1f600}".repeat(27);
  assert.equal(astral.length, 54, "precondition: JS counts these as 54 units");
  assert.equal(g.too_wide([astral]), false, "27 code points is under the 80 default");
  assert.equal(g.too_wide(["x".repeat(81)]), true);
});

test("class settings are read through this.constructor, so subclasses can override", () => {
  // Rule 1. A bare `this.STAR_EXCEPT` reads back `undefined` from an instance method
  // with no error — the failure mode that had to be swept out of src/parser.js.
  class Weird extends Generator {
    static STAR_EXCEPT = "MINUS";
  }
  const star = new exp.Star({ except_: [exp.Literal.string("a")] }, { skipInitHook: true });
  assert.equal(new Generator().sql(star), "* EXCEPT ('a')");
  assert.equal(new Weird().sql(star), "* MINUS ('a')");
});

test("a dialect NAME is refused rather than silently defaulting", () => {
  // CONTRACTS.md §8, same rule Tokenizer and Parser already enforce: falling back to
  // the default dialect would make every per-dialect generate-oracle row vacuously
  // green.
  assert.throws(() => new Generator({ dialect: "snowflake" }), /dialects\/dialect\.js is P5/);
  assert.equal(new Generator().dialect, BASE_DIALECT_GENERATOR_SETTINGS);
  assert.equal(new Generator({ dialect: null }).dialect, BASE_DIALECT_GENERATOR_SETTINGS);
});

test("SUPPORTED_JSON_PATH_PARTS is the trait-derived ALL_JSON_PATH_PARTS, not a throw", () => {
  // `sqlglot/jsonpath.py` (the tokenizer + `parse()`) is still unported, but its
  // `ALL_JSON_PATH_PARTS` constant doesn't need it -- it's exactly the ten expression
  // classes tagged `traits: ["JSONPathPart"]`, which `_gen/expr_meta.js` already
  // carries. The base Generator supports all ten, matching upstream's
  // `SUPPORTED_JSON_PATH_PARTS = ALL_JSON_PATH_PARTS.copy()`; only a dialect subclass
  // (e.g. Snowflake) narrows it.
  const want = [
    "JSONPathFilter", "JSONPathKey", "JSONPathRecursive", "JSONPathRoot",
    "JSONPathScript", "JSONPathSelector", "JSONPathSlice", "JSONPathSubscript",
    "JSONPathUnion", "JSONPathWildcard",
  ].sort();
  const got = [...Generator.SUPPORTED_JSON_PATH_PARTS].map((c) => c.name).sort();
  assert.deepEqual(got, want);

  // `.copy()` semantics: mutating one read must not affect the next.
  Generator.SUPPORTED_JSON_PATH_PARTS.clear();
  assert.equal(Generator.SUPPORTED_JSON_PATH_PARTS.size, 10);
});

test("property_sql renders a missed lookup as Python's 'None', not 'undefined'", () => {
  // Found by adversarial review. `PROPERTY_TO_NAME.get()` misses for several real,
  // reachable property classes; Python's f-string then renders `str(None)` = "None"
  // while a JS template literal renders "undefined". Reachable and observable:
  // StorageHandlerProperty has no PROPERTY_TO_NAME entry and no *_sql method, so it
  // lands in property_sql, one of sql()'s only two fallbacks. CPython @ 91119bc emits
  // exactly "None='x'" — verified directly, not reasoned about.
  const g = new Generator();
  const node = new exp.StorageHandlerProperty({ this: exp.Literal.string("x") });
  assert.equal(g.sql(node), "None='x'");
  assert.deepEqual(g.unsupported_messages, ["Unsupported property storagehandlerproperty"]);
});

test("sql() raises PyValueError, the port's stand-in for Python's ValueError", () => {
  // Upstream generator.py:1131 is `raise ValueError`. A JS TypeError is neither that
  // type nor a PyException, so it would be invisible to `instanceof PyValueError`.
  assert.throws(
    () => new Generator().sql(new exp.Expr({})),
    (e) => e instanceof PyValueError && /Unsupported expression type Expr/.test(e.message),
  );
});

test("a trailing enum ARGUMENT is not mistaken for an options object", () => {
  // `exp.DType.*` and `Properties.Location.*` are plain frozen objects, so the naive
  // `constructor === Object` options test swallows them and drops the argument from the
  // output with no error. Not reachable from any upstream call site today — which is
  // exactly the kind of "safe for now" that R18 records as expiring silently, with 426
  // stubs still to be written against these signatures.
  const g = new Generator();
  assert.equal(exp.DType.VARCHAR.constructor, Object, "precondition: DType is a plain object");
  // The enum must survive into format_args and be rendered (or fail loudly), never
  // vanish. Rendering an unsupported node type raises — that is the loud outcome.
  assert.throws(() => g.func("F", exp.Literal.string("a"), exp.DType.VARCHAR), PyValueError);
  // ...whereas a real options object is still consumed. `suffix` REPLACES the default
  // ")" rather than being appended to it, so this is "F('a']" — confirmed against
  // CPython, which emits the same.
  assert.equal(g.func("F", exp.Literal.string("a"), { suffix: "]" }), "F('a']");
});

test("the Generator composes with the real P5 Dialect", async () => {
  // CROSS-BRANCH INTEGRATION BOUNDARY. `dialects/dialect.js` (R20, p5-dialect-class)
  // and this file (R21) were built in parallel against the same CONTRACTS.md §8 rule,
  // and nothing else checks that they actually fit. `Dialect.generator_class` is still
  // `null` with a "P4" comment — wiring it is dialect.js's line to write, not this
  // branch's — so the composition that matters right now is the other direction: a
  // real resolved `Dialect` must satisfy everything the generator reads off
  // `this.dialect`.
  //
  // If this test fails after a change to dialect.js, the fix is one of: add the field
  // there, or (if upstream really lacks it) remove the read here. Do NOT "fix" it by
  // widening BASE_DIALECT_GENERATOR_SETTINGS to paper over a missing field — R18(d)
  // records a wrong output row caused by exactly that shape of stand-in.
  const { Dialect } = await import("../src/dialects/dialect.js");
  const dialect = Dialect.get_or_raise(null);

  // DERIVED from the stand-in's own keys, not a hand-written list — so a field added
  // to BASE_DIALECT_GENERATOR_SETTINGS is automatically checked against a real Dialect
  // and cannot quietly become a stand-in-only value. This closes the loop on the exact
  // failure the P3 harness had: `standInDialect` returned a plain object whose settings
  // were OWN properties, which is why ~40 `this.dialect.X` reads in parser.js looked
  // fine there and read `undefined` against the real class (R20).
  const NEEDED = Object.keys(BASE_DIALECT_GENERATOR_SETTINGS).filter((k) => k !== "tokenizer_class");
  assert.ok(NEEDED.length >= 9, "precondition: the stand-in declares the fields we read");
  assert.deepEqual(
    NEEDED.filter((k) => dialect[k] === undefined),
    [],
    "a real Dialect must carry every field the stand-in declares",
  );
  assert.ok(dialect.tokenizer_class?.STRING_ESCAPES?.length, "STRING_ESCAPES is read in the ctor");

  // ...and the base Dialect must produce the same SQL as the hardcoded stand-in, or
  // the stand-in is lying about what the base dialect does.
  const g = new Generator({ dialect });
  assert.equal(g.sql(exp.Literal.string("it's")), "'it''s'");
  assert.equal(g.sql(new exp.Abs({ this: exp.Literal.number(1) })), "ABS(1)");
  assert.equal(g.sql(exp.Literal.string("it's")), new Generator().sql(exp.Literal.string("it's")));
});

test("the seeded skeleton's size is stated, not implied", () => {
  // R13's demand made executable: the burndown numbers live in a test, so a PR that
  // ports stubs updates them deliberately.
  const sqlMethods = Object.getOwnPropertyNames(Generator.prototype).filter((n) => n.endsWith("_sql"));
  assert.equal(sqlMethods.length, 432, "upstream has 432 *_sql methods (424 public + 8 private)");

  // TWO numbers, because they are genuinely different and collapsing them would hide the
  // more interesting one.
  //
  //   HAS A BODY          the source is not a lone `throw new NotPorted`
  //   RUNS ON THE STAND-IN it also survives `new Generator()`, i.e. the default
  //                        BASE_DIALECT_GENERATOR_SETTINGS can serve everything it reads
  //
  // `identifier_sql` is the first ported method where these differ: it is fully ported
  // and verified against CPython (spike/p4/fuzz_identifier_sql.mjs, 1,160 exact over the
  // flag space), but it calls `this.dialect.can_quote`, and the stand-in is a frozen
  // data object that deliberately hosts no Dialect METHODS — a second copy of `can_quote`
  // there would be a stand-in that diverges from what it stands in for (R18(d)). It
  // therefore announces `NotPorted` on a bare `new Generator()` and works on every real
  // path, all of which pass a resolved Dialect. Wiring `Dialect.generator_class` is the
  // P5 line that collapses these two numbers back into one.
  const ONLY_THROWS = /^[^(]*\([^)]*\)\s*\{\s*throw new NotPorted\([^)]*\);?\s*\}$/;
  const bodied = sqlMethods.filter(
    (n) => !ONLY_THROWS.test(Function.prototype.toString.call(Generator.prototype[n]).trim()),
  );
  // 6 at the blocking step; +2 (`column_sql`, `identifier_sql`) from the keystone group
  // `tools/closure_generator.mjs --curve` identified; +42 from the P4 "render a basic
  // SELECT statement" keystone-group step (select_sql/query_modifiers/prepend_ctes/
  // table_sql/from_sql/cast_sql/connector_sql/... and their connective glue — see
  // PORT_PLAN.md). `binary`, `op_expressions` and `table_parts`, which that same step
  // also ported, are not `*_sql`-suffixed and so not counted here. +29 from the
  // Databricks-chain generator step (PORT_PLAN.md R31 — `src/generators/
  // {hive,spark2,spark,databricks}.js` land): `bracket_sql`/`escape_sql`/`_like_sql`/
  // `like_sql`/`ilike_sql`/`trim_sql`/`interval_sql`/`var_sql`/`exists_sql`/
  // `columndef_sql`/`schema_sql`/`schema_columns_sql`/`version_sql`/`_jsonpathkey_sql`/
  // `ignorenulls_sql`/`national_sql`/`cluster_sql`/`distribute_sql`/`sort_sql`/
  // `struct_sql`/`altercolumn_sql`/`_alter_column_null_constraint_sql`/
  // `renamecolumn_sql`/`lambda_sql`/`lateral_sql`/`placeholder_sql`/`trycast_sql`/
  // `ifblock_sql`/`jsonpath_sql` — every one of them a base method that one of the four
  // new generator classes' own overrides, its `TRANSFORMS` table, or its
  // `query_modifiers`-reached `AFTER_HAVING_MODIFIER_TRANSFORMS` entries call, which no
  // earlier dialect had exercised (the DML-only `CLUSTER BY`/`DISTRIBUTE BY`/`SORT BY`
  // trio was TODO-commented since the P4 keystone group, R25, and had no caller until
  // real HIVE corpus rows reached it here; `struct_sql`/`altercolumn_sql`/
  // `renamecolumn_sql` are reached by `Spark2Generator`'s `Generator.struct_sql(self,
  // expression)`-by-name call and its two `super(HiveGenerator, self)`
  // grandparent-skip calls; `lambda_sql`/`lateral_sql` are reached by
  // `transforms.unnest_to_explode`'s `LATERAL VIEW EXPLODE` output, which every
  // `HiveGenerator`-descended `exp.Select` TRANSFORMS entry chains in; `jsonpath_sql`
  // is reached by `DatabricksGenerator`'s own override, which calls
  // `super().jsonpath_sql(expression)`). `bracket_offset_expressions`,
  // `json_path_part`, `_embed_ignore_nulls`, `naked_property`, `lateral_op`, and
  // `datatype_param_bound_limiter`, ported in the same step, are not `*_sql`-suffixed
  // and so not counted here either. +6 from PORT_PLAN.md R32 (the scoped DuckDB
  // generator step, `src/generators/duckdb.js`): `anonymous_sql`, `nullsafeeq_sql`,
  // `nullsafeneq_sql`, `case_sql`, `if_sql`, `arraysize_sql` — each a base-Generator
  // gap that a DuckDB `TRANSFORMS` lambda reaches (e.g. `UnixSeconds` round-trips a
  // `self.func(...)` string back through `exp.cast`/`maybe_parse`, which needs
  // `anonymous_sql` for the unrecognized-function-name case; `ArrayContains`'s
  // `check_null` branch chains `if_sql` -> `case_sql` -> `arraysize_sql`), not
  // DuckDB-specific code itself.
  assert.equal(bodied.length, 85, "exactly 85 *_sql methods have a real body");

  const stubs = sqlMethods.filter((n) => {
    try {
      new Generator()[n](new exp.Expr({}));
      return false;
    } catch (e) {
      return e.name === "NotPorted";
    }
  });
  assert.equal(432 - stubs.length, 84, "84 of those 85 also run without a resolved Dialect");
  assert.deepEqual(
    bodied.filter((n) => stubs.includes(n)),
    ["identifier_sql"],
    "and the one that does not is identifier_sql, for the documented reason",
  );
});
