// py: (Python stdlib `re` / `sre_parse` semantics shim — no single upstream file)
//
// sqlglot builds and uses Python regexes in places where build-time rewriting to JS
// regex literals is impossible, because the pattern is only known at runtime:
//
//   sqlglot/generator.py:1667   escape_pattern = re.compile(rf"{escape.name}(\d+)")
//   sqlglot/parsers/bigquery.py:127
//                               try:    group = re.compile(args[1].name).groups == 1
//                               except re.error: group = False
//
// Both take a *user-supplied SQL string* and hand it to `re`. So this module provides:
//
//   1. A Python-regex parser that computes `groups` / `groupindex` and Python validity
//      WITHOUT executing anything (the oracle `bigquery.py:127` needs).
//   2. A translator from Python regex source to a JS RegExp with matching semantics.
//   3. `pyReEscape` — CPython `re.escape` semantics, emitting `/u`-safe output.
//   4. `re.sub` replacement-template translation (`\1`, `\g<name>`  ->  `$1`, `$<name>`).
//
// The oracle and the translator MUST agree on group numbering, so they are the same
// single pass: `parsePattern()` always produces group data, and separately records
// whether a JS translation was possible. A pattern that JS cannot express still
// yields correct `groups` — that is exactly the `bigquery.py:127` path.
//
// Semantics are pinned to CPython 3.9 (the toolchain floor in PORT_PLAN.md §5.2).
// Version-sensitive behaviours are marked `VERSION-SENSITIVE` in comments below and
// reported through `parsePattern().versionNotes`.

/* ------------------------------------------------------------------ flags */

export const NOFLAG = 0;
export const A = 256;
export const ASCII = 256;
export const I = 2;
export const IGNORECASE = 2;
export const L = 4;
export const LOCALE = 4;
export const M = 8;
export const MULTILINE = 8;
export const S = 16;
export const DOTALL = 16;
export const X = 64;
export const VERBOSE = 64;
export const U = 32;
export const UNICODE = 32;

/* ------------------------------------------------------------------ errors */

/** Mirror of Python's `re.error`. */
export class PyReError extends Error {
  /**
   * @param {string} msg
   * @param {string} [pattern]
   * @param {number} [pos]
   */
  constructor(msg, pattern, pos) {
    super(pos === undefined ? msg : `${msg} at position ${pos}`);
    this.name = "PyReError";
    this.msg = msg;
    this.pattern = pattern;
    this.pos = pos;
  }
}

/**
 * Raised when a pattern is valid Python but has no faithful JS RegExp encoding.
 * Never raised by the oracle path (`pyReGroups` / `pyReParse`).
 */
export class PyReUntranslatable extends Error {
  /** @param {string} reason @param {string} [pattern] */
  constructor(reason, pattern) {
    super(`cannot translate Python regex to JavaScript: ${reason}`);
    this.name = "PyReUntranslatable";
    this.reason = reason;
    this.pattern = pattern;
  }
}

/* -------------------------------------------------- character-class sources
 *
 * Derived by a full 0..0x10FFFF sweep of CPython 3.9.25's `\w`, `\d`, `\s`
 * against candidate JS property escapes (spike/regex/corpus/py_unicode_classes.json,
 * regenerated by spike/py/gen_regex_cases.py --sweep).
 *
 *   \w  ==  [\p{L}\p{Nd}\p{Nl}\p{No}_]        0 CPython-only code points
 *   \d  ==  \p{Nd}                            0 CPython-only code points
 *   \s  ==  [\t\n\x0b\f\r\x20\x1c-\x1f\x85\p{Zs}  ]   exact, both directions
 *
 * `\w` and `\d` differ from CPython only on code points that CPython 3.9's Unicode
 * 13.0 database has as *unassigned* and Node 22's ICU 16.0 has as assigned
 * (9,917 and 110 code points respectively). That is a Unicode-database version skew,
 * not a semantic difference — see spike/regex/FINDINGS.md.
 */
const WORD_U = "\\p{L}\\p{Nd}\\p{Nl}\\p{No}_";
const DIGIT_U = "\\p{Nd}";
const SPACE_U = "\\t\\n\\x0b\\f\\r\\x20\\x1c-\\x1f\\x85\\p{Zs}\\u2028\\u2029";
const WORD_A = "A-Za-z0-9_";
const DIGIT_A = "0-9";
const SPACE_A = "\\t\\n\\x0b\\f\\r\\x20";

/* ---------------------------------------------------------------- charsets */

const DIGITS = "0123456789";
const OCTDIGITS = "01234567";
const HEXDIGITS = "0123456789abcdefABCDEF";
const ASCIILETTERS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
// py: sre_parse.WHITESPACE
const RE_WHITESPACE = " \t\n\r\v\f";

// py: sre_parse.ESCAPES — `\` + letter forms that denote a literal code point.
const ESCAPE_CHARS = {
  a: 0x07,
  b: 0x08, // only inside a character class; outside it is a word boundary
  f: 0x0c,
  n: 0x0a,
  r: 0x0d,
  t: 0x09,
  v: 0x0b,
  "\\": 0x5c,
};

// py: sre_parse.CATEGORIES — valid only outside a character class for \A \Z \b \B
const CATEGORY_CHARS = new Set(["d", "D", "s", "S", "w", "W"]);
const AT_CHARS = new Set(["A", "Z", "b", "B"]);

const MAXREPEAT = 4294967295;

/* ------------------------------------------------------------- JS emission */

/**
 * Emit one code point so that it is a literal in a JS `u`- or `v`-flag pattern,
 * both inside and outside a character class. Alphanumerics pass through for
 * readability; everything else becomes a numeric escape, which is inert under
 * every JS class-syntax rule (including `v`-mode's reserved punctuators).
 * @param {number} cp
 * @returns {string}
 */
function emitCp(cp) {
  if (
    (cp >= 0x30 && cp <= 0x39) ||
    (cp >= 0x41 && cp <= 0x5a) ||
    (cp >= 0x61 && cp <= 0x7a)
  ) {
    return String.fromCodePoint(cp);
  }
  if (cp <= 0xff) return "\\x" + cp.toString(16).padStart(2, "0");
  if (cp <= 0xffff) return "\\u" + cp.toString(16).padStart(4, "0");
  return "\\u{" + cp.toString(16) + "}";
}

let _groupNameOk = new Map();
/**
 * Is `name` usable verbatim as a JS named-capture-group name? Decided by asking
 * the engine rather than by reimplementing `RegExpIdentifierName`.
 * @param {string} name
 */
function jsGroupNameOk(name) {
  const cached = _groupNameOk.get(name);
  if (cached !== undefined) return cached;
  let ok;
  try {
    new RegExp(`(?<${name}>)`, "u");
    ok = true;
  } catch {
    ok = false;
  }
  _groupNameOk.set(name, ok);
  return ok;
}

/* ------------------------------------------------------------------ parser */

/**
 * @typedef {object} PyRePatternInfo
 * @property {number} groups            capture-group count (CPython `Pattern.groups`)
 * @property {Record<string,number>} groupIndex  name -> group number (`Pattern.groupindex`)
 * @property {string|null} jsSource     translated JS pattern source, or null
 * @property {string} jsFlags           JS flags to pair with `jsSource`
 * @property {string|null} untranslatable  reason JS cannot express this, or null
 * @property {string[]} versionNotes    CPython-version-sensitive constructs seen
 * @property {Record<string,string>} jsGroupNames  python name -> emitted JS name
 */

/**
 * Parse a Python regex. Always computes `groups` / `groupIndex` / Python validity.
 * Throws {@link PyReError} for input CPython would reject; never throws for input
 * CPython accepts (untranslatable-to-JS is reported, not thrown).
 *
 * @param {string} pattern
 * @param {number} [flags]
 * @returns {PyRePatternInfo}
 */
export function pyReParse(pattern, flags = 0) {
  if (typeof pattern !== "string") throw new TypeError("pattern must be a string");
  if (flags & LOCALE) {
    throw new PyReError("cannot use LOCALE flag with a str pattern", pattern);
  }
  if (flags & ASCII && flags & UNICODE) {
    throw new PyReError("ASCII and UNICODE flags are incompatible", pattern);
  }
  // py: sre_parse.parse — a global inline flag group applies to the WHOLE pattern,
  // including the part already scanned, so CPython re-parses from scratch when one
  // turns up mid-pattern ("to be on the safe side, we'll parse the whole thing
  // again"). VERBOSE changes tokenization and MULTILINE/DOTALL change what `^ $ .`
  // compile to, so a single forward pass would silently mis-handle `a(?x)b`.
  let effective = flags;
  for (let pass = 0; ; pass += 1) {
    const p = new _Parser(pattern, effective);
    const info = p.run();
    if (p.addedGlobalFlags === 0 || pass >= 2) return info;
    effective |= p.addedGlobalFlags;
  }
}

class _Parser {
  /** @param {string} src @param {number} flags */
  constructor(src, flags) {
    /** @type {number[]} */
    this.cp = Array.from(src, (c) => /** @type {number} */ (c.codePointAt(0)));
    this.src = src;
    this.i = 0;
    this.flags = flags;
    this.groups = 0; // number of capture groups opened so far
    /** @type {Record<string,number>} */
    this.groupIndex = {};
    /** @type {Set<number>} */
    this.openGroups = new Set();
    /** @type {string[]} */
    this.versionNotes = [];
    /** @type {string|null} */
    this.untranslatable = null;
    this.needsV = false;
    /** @type {Record<string,string>} */
    this.jsGroupNames = {};
    /** flags switched on by a `(?flags)` group during this pass */
    this.addedGlobalFlags = 0;
  }

  /* --------------------------------------------------------- scan helpers */

  eof() {
    return this.i >= this.cp.length;
  }
  /** @returns {string} */
  peek(k = 0) {
    const c = this.cp[this.i + k];
    return c === undefined ? "" : String.fromCodePoint(c);
  }
  /** @returns {string} */
  next() {
    const c = this.cp[this.i];
    if (c === undefined) return "";
    this.i += 1;
    return String.fromCodePoint(c);
  }
  /** @param {string} c */
  match(c) {
    if (this.peek() === c) {
      this.i += 1;
      return true;
    }
    return false;
  }
  /** @param {string} msg @param {number} [pos] */
  err(msg, pos) {
    return new PyReError(msg, this.src, pos === undefined ? this.i : pos);
  }
  /** @param {string} reason */
  cannotTranslate(reason) {
    if (this.untranslatable === null) this.untranslatable = reason;
  }

  get verbose() {
    return (this.flags & VERBOSE) !== 0;
  }
  get ascii() {
    return (this.flags & ASCII) !== 0;
  }

  /** Skip `re.VERBOSE` whitespace and `#` comments (outside character classes). */
  skipVerbose() {
    if (!this.verbose) return;
    for (;;) {
      const c = this.peek();
      if (c !== "" && RE_WHITESPACE.includes(c)) {
        this.i += 1;
        continue;
      }
      if (c === "#") {
        while (!this.eof() && this.peek() !== "\n") this.i += 1;
        continue;
      }
      return;
    }
  }

  /* ------------------------------------------------------------------ run */

  /** @returns {PyRePatternInfo} */
  run() {
    const js = this.parseAlternation(0);
    if (!this.eof()) {
      // only reachable via a stray ')'
      throw this.err("unbalanced parenthesis");
    }
    let jsFlags = "u";
    if (this.needsV) jsFlags = "v";
    if (this.flags & IGNORECASE) jsFlags += "i";
    if (this.flags & DOTALL) jsFlags += "s";

    let jsSource = this.untranslatable === null ? js : null;
    if (jsSource !== null) {
      // Final guard: the engine is the authority on whether our emission compiles.
      try {
        new RegExp(jsSource, jsFlags);
      } catch (e) {
        jsSource = null;
        this.cannotTranslate(`emitted source rejected by engine: ${/** @type {Error} */ (e).message}`);
      }
    }
    return {
      groups: this.groups,
      groupIndex: this.groupIndex,
      jsSource,
      jsFlags,
      untranslatable: this.untranslatable,
      versionNotes: this.versionNotes,
      jsGroupNames: this.jsGroupNames,
    };
  }

  /* ---------------------------------------------------------- alternation */

  /** @param {number} depth @returns {string} */
  parseAlternation(depth) {
    const branches = [this.parseSequence(depth)];
    while (this.peekOperator("|")) {
      this.i += 1;
      branches.push(this.parseSequence(depth));
    }
    return branches.length === 1 ? branches[0] : branches.join("|");
  }

  /**
   * In VERBOSE mode `|` may be preceded by ignorable whitespace; `parseSequence`
   * already consumed it, so a plain lookahead is enough.
   * @param {string} c
   */
  peekOperator(c) {
    return this.peek() === c;
  }

  /** @param {number} depth @returns {string} */
  parseSequence(depth) {
    /** @type {string[]} */
    const out = [];
    for (;;) {
      this.skipVerbose();
      if (this.eof()) break;
      const c = this.peek();
      if (c === "|") break;
      if (c === ")") {
        if (depth === 0) throw this.err("unbalanced parenthesis");
        break;
      }
      const atom = this.parseAtom(depth);
      if (atom === null) continue; // e.g. a (?#comment) or an inline flag group
      const quantified = this.parseQuantifier(atom);
      out.push(quantified);
    }
    return out.join("");
  }

  /* ----------------------------------------------------------- quantifier */

  /**
   * @param {{js:string, repeatable:boolean, isRepeat:boolean, assertion:boolean}} atom
   * @returns {string}
   */
  parseQuantifier(atom) {
    this.skipVerbose();
    const start = this.i;
    const c = this.peek();
    let spec = null;
    if (c === "*" || c === "+" || c === "?") {
      this.i += 1;
      spec = c;
    } else if (c === "{") {
      spec = this.parseBraceQuantifier();
      if (spec === null) {
        // CPython treats a non-quantifier '{' as a literal; `parseBraceQuantifier`
        // has already rewound, so fall through and let the caller re-read it.
        this.i = start;
        return atom.js;
      }
    } else {
      return atom.js;
    }

    if (!atom.repeatable) {
      throw this.err("nothing to repeat", start);
    }
    if (atom.isRepeat) {
      throw this.err("multiple repeat", start);
    }

    // greedy / non-greedy / possessive
    let suffix = "";
    if (this.match("?")) {
      suffix = "?";
    } else if (this.peek() === "+") {
      // py: possessive quantifiers are CPython 3.11+; 3.9 reports "multiple repeat"
      throw this.err("multiple repeat", this.i);
    }

    // JS `u` mode forbids quantifying an assertion; Python allows it. `(?:^)*`
    // is the equivalent and is accepted by both engines.
    const base = atom.assertion ? `(?:${atom.js})` : atom.js;
    return base + spec + suffix;
  }

  /**
   * py: sre_parse._parse, the `this == "{"` branch. Returns null when CPython
   * would treat the brace as a literal (leaving the cursor untouched).
   * @returns {string|null}
   */
  parseBraceQuantifier() {
    const here = this.i;
    this.i += 1; // consume '{'
    if (this.peek() === "}") {
      this.i = here;
      return null; // "{}" is a literal pair
    }
    let lo = "";
    let hi = "";
    while (this.peek() !== "" && DIGITS.includes(this.peek())) lo += this.next();
    let comma = false;
    if (this.match(",")) {
      comma = true;
      while (this.peek() !== "" && DIGITS.includes(this.peek())) hi += this.next();
    } else {
      hi = lo;
    }
    if (!this.match("}")) {
      this.i = here;
      return null;
    }
    const min = lo === "" ? 0 : Number(lo);
    const max = hi === "" ? MAXREPEAT : Number(hi);
    if (min >= MAXREPEAT) throw this.err("the repetition number is too large", here);
    if (max >= MAXREPEAT && hi !== "") {
      throw this.err("the repetition number is too large", here);
    }
    if (max < min) throw this.err("min repeat greater than max repeat", here + 1);
    // JS `u` rejects `{,n}`; CPython reads it as `{0,n}`.
    if (!comma) return `{${min}}`;
    if (hi === "") return `{${min},}`;
    return `{${min},${max}}`;
  }

  /* ----------------------------------------------------------------- atom */

  /**
   * @param {number} depth
   * @returns {{js:string, repeatable:boolean, isRepeat:boolean, assertion:boolean}|null}
   */
  parseAtom(depth) {
    const c = this.next();
    switch (c) {
      case "(":
        return this.parseGroup(depth);
      case "[":
        return { js: this.parseCharClass(), repeatable: true, isRepeat: false, assertion: false };
      case ".":
        // CPython `.` excludes exactly U+000A. JS `.` additionally excludes
        // \r, U+2028 and U+2029 — so only the DOTALL form can use `.`.
        return {
          js: this.flags & DOTALL ? "." : "[^\\n]",
          repeatable: true,
          isRepeat: false,
          assertion: false,
        };
      case "^":
        return {
          js: this.flags & MULTILINE ? "(?:^|(?<=\\n))" : "^",
          repeatable: true,
          isRepeat: false,
          assertion: true,
        };
      case "$":
        // CPython `$` (no MULTILINE) also matches just before a trailing newline;
        // JS `$` without `m` does not. MULTILINE `$` matches before every newline,
        // but JS `m` additionally splits on \r, U+2028 and U+2029.
        return {
          js: this.flags & MULTILINE ? "(?=\\n|$)" : "(?=\\n?$)",
          repeatable: true,
          isRepeat: false,
          assertion: true,
        };
      case "*":
      case "+":
      case "?":
        throw this.err("nothing to repeat", this.i - 1);
      case "\\":
        return this.parseEscape();
      default: {
        const cp = /** @type {number} */ (c.codePointAt(0));
        return { js: emitCp(cp), repeatable: true, isRepeat: false, assertion: false };
      }
    }
  }

  /* --------------------------------------------------------------- groups */

  /**
   * @param {number} depth
   * @returns {{js:string, repeatable:boolean, isRepeat:boolean, assertion:boolean}|null}
   */
  parseGroup(depth) {
    const open = this.i - 1;
    if (!this.match("?")) {
      // plain capturing group
      this.groups += 1;
      const gid = this.groups;
      this.openGroups.add(gid);
      const body = this.parseAlternation(depth + 1);
      if (!this.match(")")) throw this.err("missing ), unterminated subpattern", open);
      this.openGroups.delete(gid);
      return { js: `(${body})`, repeatable: true, isRepeat: false, assertion: false };
    }

    const c = this.peek();

    // (?P...) — named group, named backreference
    if (c === "P") {
      this.i += 1;
      if (this.match("<")) {
        const name = this.readGroupName(">");
        if (Object.prototype.hasOwnProperty.call(this.groupIndex, name)) {
          throw this.err(`redefinition of group name '${name}'`, open);
        }
        this.groups += 1;
        const gid = this.groups;
        this.groupIndex[name] = gid;
        this.openGroups.add(gid);
        const body = this.parseAlternation(depth + 1);
        if (!this.match(")")) throw this.err("missing ), unterminated subpattern", open);
        this.openGroups.delete(gid);
        const jsName = jsGroupNameOk(name) ? name : `_g${gid}`;
        this.jsGroupNames[name] = jsName;
        return {
          js: `(?<${jsName}>${body})`,
          repeatable: true,
          isRepeat: false,
          assertion: false,
        };
      }
      if (this.match("=")) {
        const name = this.readGroupName(")");
        const gid = this.groupIndex[name];
        if (gid === undefined) throw this.err(`unknown group name '${name}'`, this.i);
        const jsName = this.jsGroupNames[name];
        return {
          js: `\\k<${jsName}>`,
          repeatable: true,
          isRepeat: false,
          assertion: false,
        };
      }
      throw this.err("unknown extension ?P", open + 1);
    }

    // (?:...)
    if (c === ":") {
      this.i += 1;
      const body = this.parseAlternation(depth + 1);
      if (!this.match(")")) throw this.err("missing ), unterminated subpattern", open);
      return { js: `(?:${body})`, repeatable: true, isRepeat: false, assertion: false };
    }

    // (?#...)
    if (c === "#") {
      this.i += 1;
      for (;;) {
        if (this.eof()) throw this.err("missing ), unterminated comment", open);
        if (this.next() === ")") break;
      }
      return null;
    }

    // (?=...) (?!...)
    if (c === "=" || c === "!") {
      this.i += 1;
      const body = this.parseAlternation(depth + 1);
      if (!this.match(")")) throw this.err("missing ), unterminated subpattern", open);
      return {
        js: `(?${c}${body})`,
        repeatable: true,
        isRepeat: false,
        assertion: true,
      };
    }

    // (?<=...) (?<!...)
    if (c === "<") {
      const dir = this.peek(1);
      if (dir === "=" || dir === "!") {
        this.i += 2;
        const body = this.parseAlternation(depth + 1);
        if (!this.match(")")) throw this.err("missing ), unterminated subpattern", open);
        // CPython requires fixed-width lookbehind; JS does not. Every pattern
        // CPython accepts is therefore accepted by JS.
        return {
          js: `(?<${dir}${body})`,
          repeatable: true,
          isRepeat: false,
          assertion: true,
        };
      }
      throw this.err(`unknown extension ?<${dir}`, open + 1);
    }

    // (?(id/name)yes|no)
    if (c === "(") {
      this.i += 1;
      const cond = this.readGroupName(")");
      if (/^\d+$/.test(cond)) {
        const n = Number(cond);
        if (n === 0) throw this.err("bad group number", this.i);
        if (n > this.groups) throw this.err(`invalid group reference ${n}`, this.i);
      } else if (this.groupIndex[cond] === undefined) {
        throw this.err(`unknown group name '${cond}'`, this.i);
      }
      // Consume the yes/no branches so group numbering stays correct.
      this.parseAlternation(depth + 1);
      if (!this.match(")")) throw this.err("missing ), unterminated subpattern", open);
      this.cannotTranslate("conditional group (?(id)yes|no) has no JS equivalent");
      return { js: "", repeatable: true, isRepeat: false, assertion: false };
    }

    // (?>...) atomic group — CPython 3.11+
    if (c === ">") {
      throw this.err("unknown extension ?>", open + 1);
    }

    // (?aiLmsux) / (?aiLmsux-imsx:...)
    return this.parseFlagGroup(open, depth);
  }

  /**
   * @param {number} open
   * @param {number} depth
   * @returns {{js:string, repeatable:boolean, isRepeat:boolean, assertion:boolean}|null}
   */
  parseFlagGroup(open, depth) {
    const FLAG_CHARS = { a: ASCII, i: IGNORECASE, L: LOCALE, m: MULTILINE, s: DOTALL, u: UNICODE, x: VERBOSE };
    let add = 0;
    let seenAny = false;
    for (;;) {
      const ch = this.peek();
      if (ch === "" || !(ch in FLAG_CHARS)) break;
      add |= FLAG_CHARS[/** @type {keyof typeof FLAG_CHARS} */ (ch)];
      this.i += 1;
      seenAny = true;
    }
    if (this.peek() === "-" || this.peek() === ":") {
      // scoped form (?i:...) or (?i-s:...)
      let remove = 0;
      if (this.match("-")) {
        for (;;) {
          const ch = this.peek();
          if (ch === "" || !(ch in FLAG_CHARS)) break;
          remove |= FLAG_CHARS[/** @type {keyof typeof FLAG_CHARS} */ (ch)];
          this.i += 1;
        }
        if (remove === 0) throw this.err("missing flag", this.i);
        if (remove & (ASCII | LOCALE | UNICODE)) {
          throw this.err("bad inline flags: cannot turn off flags 'a', 'u' and 'L'", this.i);
        }
      }
      if (!this.match(":")) throw this.err("missing :", this.i);
      // Node 22 does not implement ES2025 regex modifier groups `(?i:...)`.
      this.cannotTranslate("scoped inline flags (?flags:...) are unsupported by this JS engine");
      const body = this.parseAlternation(depth + 1);
      if (!this.match(")")) throw this.err("missing ), unterminated subpattern", open);
      return { js: `(?:${body})`, repeatable: true, isRepeat: false, assertion: false };
    }
    if (!seenAny) throw this.err(`unknown extension ?${this.peek()}`, open + 1);
    if (!this.match(")")) throw this.err("missing -, : or )", this.i);
    if (add & LOCALE) throw this.err("bad inline flags: cannot use 'L' flag with a str pattern", this.i);
    if (add & ASCII && (this.flags | add) & UNICODE) {
      throw this.err("ASCII and UNICODE flags are incompatible", this.i);
    }
    // Global inline flags. VERSION-SENSITIVE: CPython <=3.10 only warns when these
    // are not at the start of the pattern; 3.11+ raises
    // `re.error: global flags not at the start of the expression`.
    if (open !== 0) {
      this.versionNotes.push(
        `global inline flags at position ${open}: DeprecationWarning on CPython <=3.10, re.error on 3.11+`,
      );
    }
    this.addedGlobalFlags |= add & ~this.flags;
    this.flags |= add;
    return null;
  }

  /**
   * py: sre_parse — group names must satisfy `str.isidentifier()`.
   * @param {string} terminator
   */
  readGroupName(terminator) {
    let name = "";
    for (;;) {
      if (this.eof()) throw this.err(`missing ${terminator}, unterminated name`, this.i);
      const ch = this.next();
      if (ch === terminator) break;
      name += ch;
    }
    if (name === "") throw this.err("missing group name", this.i);
    if (terminator === ")" && /^\d+$/.test(name)) return name; // conditional by number
    if (!isPyIdentifier(name)) throw this.err(`bad character in group name '${name}'`, this.i);
    return name;
  }

  /* --------------------------------------------------------------- escape */

  /**
   * py: sre_parse._escape (outside a character class).
   * @returns {{js:string, repeatable:boolean, isRepeat:boolean, assertion:boolean}}
   */
  parseEscape() {
    if (this.eof()) throw this.err("bad escape (end of pattern)", this.i - 1);
    const start = this.i - 1;
    const c = this.next();

    if (AT_CHARS.has(c)) {
      switch (c) {
        case "A":
          return { js: "^", repeatable: true, isRepeat: false, assertion: true };
        case "Z":
          return { js: "$", repeatable: true, isRepeat: false, assertion: true };
        case "b":
        case "B": {
          // CPython `\b` is Unicode-aware for str patterns; JS `\b` is always ASCII.
          const w = this.ascii ? WORD_A : WORD_U;
          const inside = `(?:(?<![${w}])(?=[${w}])|(?<=[${w}])(?![${w}]))`;
          const js = c === "b" ? inside : `(?!${inside})`;
          return { js, repeatable: true, isRepeat: false, assertion: true };
        }
      }
    }

    if (CATEGORY_CHARS.has(c)) {
      return {
        js: this.categorySource(c),
        repeatable: true,
        isRepeat: false,
        assertion: false,
      };
    }

    if (c in ESCAPE_CHARS) {
      return {
        js: emitCp(ESCAPE_CHARS[/** @type {keyof typeof ESCAPE_CHARS} */ (c)]),
        repeatable: true,
        isRepeat: false,
        assertion: false,
      };
    }

    if (c === "0") {
      let oct = "";
      while (oct.length < 2 && this.peek() !== "" && OCTDIGITS.includes(this.peek())) {
        oct += this.next();
      }
      return {
        js: emitCp(parseInt("0" + oct, 8) & 0xff),
        repeatable: true,
        isRepeat: false,
        assertion: false,
      };
    }

    if (DIGITS.includes(c)) {
      // py: backreference, unless the first three digits are a valid octal escape
      let digits = c;
      if (this.peek() !== "" && DIGITS.includes(this.peek())) {
        digits += this.next();
        if (
          OCTDIGITS.includes(digits[0]) &&
          OCTDIGITS.includes(digits[1]) &&
          this.peek() !== "" &&
          OCTDIGITS.includes(this.peek())
        ) {
          digits += this.next();
          const v = parseInt(digits, 8);
          if (v > 0o377) {
            throw this.err(`octal escape value \\${digits} outside of range 0-0o377`, start);
          }
          return { js: emitCp(v), repeatable: true, isRepeat: false, assertion: false };
        }
      }
      const gid = Number(digits);
      if (gid === 0) throw this.err("bad escape \\0", start);
      if (gid > this.groups) throw this.err(`invalid group reference ${gid}`, start + 1);
      if (this.openGroups.has(gid)) throw this.err("cannot refer to an open group", start);
      return { js: `\\${gid}`, repeatable: true, isRepeat: false, assertion: false };
    }

    const cp = this.readCharEscape(c, start);
    if (cp !== null) {
      return { js: emitCp(cp), repeatable: true, isRepeat: false, assertion: false };
    }

    if (ASCIILETTERS.includes(c)) throw this.err(`bad escape \\${c}`, start);
    return {
      js: emitCp(/** @type {number} */ (c.codePointAt(0))),
      repeatable: true,
      isRepeat: false,
      assertion: false,
    };
  }

  /**
   * `\xHH`, `\uXXXX`, `\UXXXXXXXX`, `\N{NAME}`, `\ooo`. Returns null if `c`
   * does not start one of those forms.
   * @param {string} c @param {number} start @returns {number|null}
   */
  readCharEscape(c, start) {
    if (c === "x") return this.readHex(2, start, "\\x");
    if (c === "u") return this.readHex(4, start, "\\u");
    if (c === "U") {
      const v = this.readHex(8, start, "\\U");
      if (v !== null && v > 0x10ffff) {
        throw this.err(`bad escape \\U`, start);
      }
      return v;
    }
    if (c === "N") {
      if (!this.match("{")) throw this.err("missing {", this.i);
      let name = "";
      for (;;) {
        if (this.eof()) throw this.err("missing }, unterminated name", this.i);
        const ch = this.next();
        if (ch === "}") break;
        name += ch;
      }
      if (name === "") throw this.err("missing character name", this.i);
      // Resolving a Unicode character *name* needs the UnicodeData name table,
      // which a zero-dependency runtime does not carry. The oracle path is
      // unaffected (0 groups); only translation is blocked.
      this.cannotTranslate("\\N{NAME} requires the Unicode character-name database");
      return 0xfffd;
    }
    if (OCTDIGITS.includes(c)) {
      let oct = c;
      while (oct.length < 3 && this.peek() !== "" && OCTDIGITS.includes(this.peek())) {
        oct += this.next();
      }
      return parseInt(oct, 8);
    }
    return null;
  }

  /** @param {number} n @param {number} start @param {string} what */
  readHex(n, start, what) {
    let hex = "";
    while (hex.length < n && this.peek() !== "" && HEXDIGITS.includes(this.peek())) {
      hex += this.next();
    }
    if (hex.length !== n) throw this.err(`incomplete escape ${what}${hex}`, start);
    return parseInt(hex, 16);
  }

  /**
   * Character-class source (without brackets) for `\d \D \s \S \w \W`, or the
   * bracketed form when used as a standalone atom.
   * @param {string} c @returns {string}
   */
  categorySource(c) {
    const inner = this.categoryInner(c.toLowerCase());
    return c === c.toLowerCase() ? `[${inner}]` : `[^${inner}]`;
  }

  /** @param {string} lower @returns {string} */
  categoryInner(lower) {
    if (lower === "d") return this.ascii ? DIGIT_A : DIGIT_U;
    if (lower === "s") return this.ascii ? SPACE_A : SPACE_U;
    return this.ascii ? WORD_A : WORD_U;
  }

  /* ---------------------------------------------------------- char class */

  /**
   * py: sre_parse._parse, the `this == "["` branch, plus `_class_escape`.
   * @returns {string}
   */
  parseCharClass() {
    const open = this.i - 1;
    const negate = this.match("^");
    /** @type {Array<{k:'cp',v:number}|{k:'range',lo:number,hi:number}|{k:'cat',c:string}>} */
    const items = [];
    let first = true;
    for (;;) {
      if (this.eof()) throw this.err("unterminated character set", open);
      // ']' in first position is a literal
      if (this.peek() === "]" && !first) {
        this.i += 1;
        break;
      }
      first = false;
      const item = this.parseClassItem(open);
      // range?
      if (
        item.k === "cp" &&
        this.peek() === "-" &&
        this.peek(1) !== "]" &&
        this.peek(1) !== ""
      ) {
        this.i += 1; // consume '-'
        const hi = this.parseClassItem(open);
        if (hi.k !== "cp") {
          throw this.err(
            `bad character range ${String.fromCodePoint(item.v)}-\\${hi.k === "cat" ? hi.c : "?"}`,
            open + 1,
          );
        }
        if (hi.v < item.v) {
          throw this.err(
            `bad character range ${String.fromCodePoint(item.v)}-${String.fromCodePoint(hi.v)}`,
            open + 1,
          );
        }
        items.push({ k: "range", lo: item.v, hi: hi.v });
        continue;
      }
      items.push(item);
    }
    if (items.length === 0) {
      // "[]" is unterminated in CPython; "[]]" is the one-element set {']'}.
      throw this.err("unterminated character set", open);
    }
    return this.emitClass(items, negate);
  }

  /**
   * @param {number} open
   * @returns {{k:'cp',v:number}|{k:'cat',c:string}}
   */
  parseClassItem(open) {
    const c = this.next();
    if (c !== "\\") return { k: "cp", v: /** @type {number} */ (c.codePointAt(0)) };
    if (this.eof()) throw this.err("bad escape (end of pattern)", this.i - 1);
    const start = this.i - 1;
    const e = this.next();
    // Inside a class, `\b` is a backspace, not a word boundary.
    if (e in ESCAPE_CHARS) {
      return { k: "cp", v: ESCAPE_CHARS[/** @type {keyof typeof ESCAPE_CHARS} */ (e)] };
    }
    if (CATEGORY_CHARS.has(e)) return { k: "cat", c: e };
    if (AT_CHARS.has(e)) throw this.err(`bad escape \\${e}`, start);
    const cp = this.readCharEscape(e, start);
    if (cp !== null) return { k: "cp", v: cp };
    if (DIGITS.includes(e)) throw this.err(`bad escape \\${e}`, start);
    if (ASCIILETTERS.includes(e)) throw this.err(`bad escape \\${e}`, start);
    return { k: "cp", v: /** @type {number} */ (e.codePointAt(0)) };
  }

  /**
   * @param {Array<{k:'cp',v:number}|{k:'range',lo:number,hi:number}|{k:'cat',c:string}>} items
   * @param {boolean} negate
   * @returns {string}
   */
  emitClass(items, negate) {
    // A negated shorthand (\W \D \S) expands to a negated set, which cannot nest
    // inside a `u`-mode class. `v` mode allows nesting, so escalate when needed.
    const negatedCats = items.filter((it) => it.k === "cat" && it.c !== it.c.toLowerCase());
    if (items.length === 1 && items[0].k === "cat") {
      const cat = /** @type {{k:'cat',c:string}} */ (items[0]);
      const inner = this.categoryInner(cat.c.toLowerCase());
      const catNegated = cat.c !== cat.c.toLowerCase();
      const finallyNegated = negate !== catNegated;
      return `[${finallyNegated ? "^" : ""}${inner}]`;
    }

    let body = "";
    for (const it of items) {
      if (it.k === "cp") body += emitCp(it.v);
      else if (it.k === "range") body += `${emitCp(it.lo)}-${emitCp(it.hi)}`;
      else {
        const inner = this.categoryInner(it.c.toLowerCase());
        if (it.c === it.c.toLowerCase()) {
          body += inner;
        } else {
          this.needsV = true;
          body += `[^${inner}]`;
        }
      }
    }
    if (negatedCats.length > 0) this.needsV = true;
    return `[${negate ? "^" : ""}${body}]`;
  }
}

/** py: `str.isidentifier()` — PEP 3131 identifier rules. */
const PY_IDENT_RE = /^[\p{L}\p{Nl}_][\p{L}\p{Nl}\p{Mn}\p{Mc}\p{Nd}\p{Pc}_]*$/u;
/** @param {string} s */
function isPyIdentifier(s) {
  return PY_IDENT_RE.test(s.normalize("NFKC"));
}

/* ---------------------------------------------------------------- oracles */

/**
 * CPython `re.compile(pattern).groups`. Throws {@link PyReError} exactly where
 * CPython raises `re.error`.
 *
 * py: sqlglot/parsers/bigquery.py:127 — `re.compile(args[1].name).groups == 1`
 * @param {string} pattern @param {number} [flags] @returns {number}
 */
export function pyReGroups(pattern, flags = 0) {
  return pyReParse(pattern, flags).groups;
}

/**
 * True iff CPython's `re.compile` would accept `pattern`.
 * @param {string} pattern @param {number} [flags] @returns {boolean}
 */
export function pyReIsValid(pattern, flags = 0) {
  try {
    pyReParse(pattern, flags);
    return true;
  } catch (e) {
    if (e instanceof PyReError) return false;
    throw e;
  }
}

/* ----------------------------------------------------------------- escape */

// py: re._special_chars_map — CPython >= 3.7 escapes exactly this set.
const PY_ESCAPE_SET = "()[]{}?*+-|^$\\.&~# \t\n\r\v\f";
// The subset that is also a legal `IdentityEscape` under a JS `u`/`v` flag.
const JS_IDENTITY_SAFE = "()[]{}?*+|^$\\.";

/**
 * CPython `re.escape` semantics, emitting output that is valid inside a JS
 * `u`-flag (and `v`-flag) pattern.
 *
 * CPython escapes `- & ~ #` and the literal whitespace characters with a bare
 * backslash; `\-`, `\&`, `\~`, `\#` and `\<TAB>` are all SyntaxErrors under `/u`,
 * so those are emitted as numeric escapes instead. The resulting regex is
 * semantically identical and re-parses cleanly through {@link pyReParse}.
 *
 * py: sqlglot/optimizer/qualify_columns.py:1176,1182 — `re.escape(pattern[i])`
 * @param {string} s @returns {string}
 */
export function pyReEscape(s) {
  let out = "";
  for (const ch of s) {
    if (PY_ESCAPE_SET.includes(ch)) {
      out += JS_IDENTITY_SAFE.includes(ch)
        ? "\\" + ch
        : emitCp(/** @type {number} */ (ch.codePointAt(0)));
    } else {
      out += ch;
    }
  }
  return out;
}

/**
 * Byte-identical reproduction of CPython's `re.escape` output. Provided for
 * differential testing and for call sites that use the result as a *string*
 * rather than as regex source; it is NOT safe to drop into a JS `/u` pattern.
 * @param {string} s @returns {string}
 */
export function pyReEscapeExact(s) {
  let out = "";
  for (const ch of s) out += PY_ESCAPE_SET.includes(ch) ? "\\" + ch : ch;
  return out;
}

/* -------------------------------------------------------- sub / templates */

/**
 * @typedef {object} PyReTemplate
 * @property {Array<{lit:string}|{group:number}>} items  parsed template
 * @property {string|null} js   JS replacement string, or null when ambiguous
 * @property {string|null} ambiguous  reason the string form is unusable
 * @property {(m: RegExpExecArray) => string} apply  always-correct expansion
 */

/**
 * Parse a CPython `re.sub` replacement template and translate it to JS.
 *
 * CPython templates use `\1`..`\99` and `\g<name>` / `\g<0>`; JS uses `$1`,
 * `$<name>` and `$&`. Notable traps, all handled here:
 *
 *   - a literal `$` in the Python template must become `$$` in JS;
 *   - `\g<0>` is the whole match, which JS spells `$&` (`$0` is literal in JS);
 *   - `\\` is a literal backslash, and backslashes are NOT special in a JS
 *     replacement string, so `\\` becomes a single `\`;
 *   - inside a template `\b` is a backspace (U+0008), not a word boundary;
 *   - `\` + an ASCII letter that is not one of `abfnrtv` is a CPython error;
 *   - `\` + a non-letter (e.g. `\-`) keeps the backslash as a literal;
 *   - `$nn` is read greedily by JS, so `\1` followed by the literal digit `2`
 *     silently becomes group 12 when the pattern has >= 12 groups. That case is
 *     reported via `ambiguous` and `js === null`; use `apply` instead.
 *
 * py: sqlglot/generator.py:1660,1663 — `r"\\\1"` and `r"\\u\1"`
 * @param {string} template
 * @param {number} groups
 * @param {Record<string,number>} [groupIndex]
 * @returns {PyReTemplate}
 */
export function pyReTemplate(template, groups, groupIndex = {}) {
  /** @type {Array<{lit:string}|{group:number}>} */
  const items = [];
  /** @param {string} s */
  const lit = (s) => {
    const last = items[items.length - 1];
    if (last && "lit" in last) last.lit += s;
    else items.push({ lit: s });
  };

  let i = 0;
  while (i < template.length) {
    const ch = template[i];
    if (ch !== "\\") {
      lit(ch);
      i += 1;
      continue;
    }
    i += 1;
    if (i >= template.length) throw new PyReError("bad escape (end of pattern)", template, i - 1);
    const c = template[i];
    i += 1;

    if (c === "g") {
      if (template[i] !== "<") throw new PyReError("missing <", template, i);
      i += 1;
      let name = "";
      for (;;) {
        if (i >= template.length) throw new PyReError("missing >, unterminated name", template, i);
        const d = template[i];
        i += 1;
        if (d === ">") break;
        name += d;
      }
      if (name === "") throw new PyReError("missing group name", template, i);
      let gid;
      if (/^-?\d+$/.test(name)) {
        gid = Number(name);
        if (gid < 0) throw new PyReError(`bad character in group name '${name}'`, template, i);
      } else {
        if (!isPyIdentifier(name)) {
          throw new PyReError(`bad character in group name '${name}'`, template, i);
        }
        gid = groupIndex[name];
        if (gid === undefined) throw new PyReError(`unknown group name '${name}'`, template, i);
      }
      if (gid > groups) throw new PyReError(`invalid group reference ${gid}`, template, i);
      items.push({ group: gid });
      continue;
    }

    if (c === "0") {
      let oct = "";
      while (oct.length < 2 && i < template.length && OCTDIGITS.includes(template[i])) {
        oct += template[i];
        i += 1;
      }
      lit(String.fromCharCode(parseInt("0" + oct, 8) & 0xff));
      continue;
    }

    if (DIGITS.includes(c)) {
      let digits = c;
      if (i < template.length && DIGITS.includes(template[i])) {
        const two = digits + template[i];
        if (
          OCTDIGITS.includes(two[0]) &&
          OCTDIGITS.includes(two[1]) &&
          i + 1 < template.length &&
          OCTDIGITS.includes(template[i + 1])
        ) {
          const three = two + template[i + 1];
          i += 2;
          const v = parseInt(three, 8);
          if (v > 0o377) {
            throw new PyReError(
              `octal escape value \\${three} outside of range 0-0o377`,
              template,
              i,
            );
          }
          lit(String.fromCharCode(v));
          continue;
        }
        digits = two;
        i += 1;
      }
      const gid = Number(digits);
      if (gid > groups) throw new PyReError(`invalid group reference ${gid}`, template, i - 1);
      items.push({ group: gid });
      continue;
    }

    if (c in ESCAPE_CHARS) {
      lit(String.fromCharCode(ESCAPE_CHARS[/** @type {keyof typeof ESCAPE_CHARS} */ (c)]));
      continue;
    }
    if (ASCIILETTERS.includes(c)) throw new PyReError(`bad escape \\${c}`, template, i - 2);
    // `\` + non-letter keeps both characters, e.g. `\-` -> `\-`
    lit("\\" + c);
  }

  // ---- JS replacement-string form, with the `$nn` greediness check ----
  let js = "";
  let ambiguous = null;
  for (let k = 0; k < items.length; k += 1) {
    const it = items[k];
    if ("lit" in it) {
      js += it.lit.replace(/\$/g, "$$$$");
      continue;
    }
    if (it.group === 0) {
      js += "$&";
      continue;
    }
    const nextItem = items[k + 1];
    const nextChar =
      nextItem && "lit" in nextItem && nextItem.lit.length > 0 ? nextItem.lit[0] : "";
    // NB: `"...".includes("")` is always true, so the empty case must be excluded.
    if (nextChar !== "" && DIGITS.includes(nextChar)) {
      const twoDigit = Number(String(it.group) + nextChar);
      // JS tries the 2-digit reading first and only falls back when it exceeds
      // the group count.
      if (it.group < 10 && twoDigit <= groups) {
        ambiguous = `\\${it.group} followed by literal '${nextChar}' is indistinguishable from $${twoDigit}`;
      }
    }
    js += "$" + it.group;
  }
  if (ambiguous !== null) js = null;

  return {
    items,
    js,
    ambiguous,
    /** @param {RegExpExecArray} m */
    apply(m) {
      let out = "";
      for (const it of items) {
        if ("lit" in it) out += it.lit;
        else out += m[it.group] === undefined ? "" : m[it.group];
      }
      return out;
    },
  };
}

/* -------------------------------------------------------------- Match/Pattern */

/** Mirror of CPython's `re.Match`. */
export class PyMatch {
  /**
   * @param {RegExpExecArray} m
   * @param {PyPattern} pattern
   * @param {string} string
   */
  constructor(m, pattern, string) {
    this._m = m;
    this.re = pattern;
    this.string = string;
    this.lastindex = null;
    for (let i = m.length - 1; i >= 1; i -= 1) {
      if (m[i] !== undefined) {
        this.lastindex = i;
        break;
      }
    }
  }
  /** @param {...(number|string)} keys */
  group(...keys) {
    if (keys.length === 0) return this._m[0];
    const vals = keys.map((k) => {
      const i = this.re._groupNumber(k);
      const v = this._m[i];
      return v === undefined ? null : v;
    });
    return keys.length === 1 ? vals[0] : vals;
  }
  groups(dflt = null) {
    const out = [];
    for (let i = 1; i < this._m.length; i += 1) {
      out.push(this._m[i] === undefined ? dflt : this._m[i]);
    }
    return out;
  }
  groupdict(dflt = null) {
    /** @type {Record<string, string|null>} */
    const out = {};
    for (const [name, gid] of Object.entries(this.re.groupindex)) {
      out[name] = this._m[gid] === undefined ? dflt : this._m[gid];
    }
    return out;
  }
  /** @param {number|string} [g] */
  start(g = 0) {
    const i = this.re._groupNumber(g);
    if (i === 0) return this._m.index;
    if (this._m[i] === undefined) return -1;
    // Node exposes per-group indices only with the `d` flag; PyPattern sets it.
    const ind = /** @type {any} */ (this._m).indices;
    return ind && ind[i] ? ind[i][0] : -1;
  }
  /** @param {number|string} [g] */
  end(g = 0) {
    const i = this.re._groupNumber(g);
    if (i === 0) return this._m.index + this._m[0].length;
    if (this._m[i] === undefined) return -1;
    const ind = /** @type {any} */ (this._m).indices;
    return ind && ind[i] ? ind[i][1] : -1;
  }
  /** @param {number|string} [g] */
  span(g = 0) {
    return [this.start(g), this.end(g)];
  }
}

/** Mirror of CPython's compiled `re.Pattern`. */
export class PyPattern {
  /** @param {string} pattern @param {number} flags */
  constructor(pattern, flags) {
    const info = pyReParse(pattern, flags);
    this.pattern = pattern;
    this.flags = flags;
    this.groups = info.groups;
    this.groupindex = info.groupIndex;
    this.versionNotes = info.versionNotes;
    this._info = info;
    if (info.jsSource === null) {
      throw new PyReUntranslatable(/** @type {string} */ (info.untranslatable), pattern);
    }
    this._src = info.jsSource;
    this._flags = info.jsFlags;
  }

  /**
   * A fresh RegExp per call: `lastIndex` is mutable state, and `sub()` with a
   * function replacement can re-enter the same pattern.
   * @param {string} extra
   */
  _re(extra) {
    return new RegExp(this._src, this._flags + extra);
  }

  /** @param {number|string} key @returns {number} */
  _groupNumber(key) {
    if (typeof key === "number") {
      if (key < 0 || key > this.groups) throw new PyReError(`no such group: ${key}`);
      return key;
    }
    const gid = this.groupindex[key];
    if (gid === undefined) throw new PyReError(`no such group: '${key}'`);
    return gid;
  }

  /** py: Pattern.match — anchored at `pos`, not required to reach the end. */
  match(string, pos = 0, endpos = undefined) {
    const s = endpos === undefined ? string : string.slice(0, endpos);
    const re = this._re("yd");
    re.lastIndex = pos;
    const m = re.exec(s);
    return m ? new PyMatch(m, this, string) : null;
  }

  /**
   * py: Pattern.fullmatch. Sticky alone is not enough — the engine returns the
   * first alternative that matches at `pos`, not the one reaching the end — so
   * the end anchor goes into the source. `$` is a true end-of-input anchor here
   * because this module never emits the JS `m` flag (MULTILINE is desugared).
   */
  fullmatch(string, pos = 0, endpos = undefined) {
    const s = endpos === undefined ? string : string.slice(0, endpos);
    const re = new RegExp(`(?:${this._src})$`, this._flags + "yd");
    re.lastIndex = pos;
    const m = re.exec(s);
    return m ? new PyMatch(m, this, string) : null;
  }

  /** py: Pattern.search */
  search(string, pos = 0, endpos = undefined) {
    const s = endpos === undefined ? string : string.slice(0, endpos);
    const re = this._re("gd");
    re.lastIndex = pos;
    const m = re.exec(s);
    return m ? new PyMatch(m, this, string) : null;
  }

  /** py: Pattern.findall */
  findall(string) {
    const re = this._re("gd");
    re.lastIndex = 0;
    const out = [];
    let m;
    while ((m = re.exec(string)) !== null) {
      // py: Pattern.findall returns the whole match with 0 groups, the single
      // group with 1, and a tuple of groups otherwise; unmatched groups are "".
      if (this.groups === 0) out.push(m[0]);
      else if (this.groups === 1) out.push(m[1] === undefined ? "" : m[1]);
      else {
        const tup = [];
        for (let i = 1; i <= this.groups; i += 1) tup.push(m[i] === undefined ? "" : m[i]);
        out.push(tup);
      }
      if (m[0] === "") re.lastIndex += 1;
    }
    return out;
  }

  /** py: Pattern.finditer */
  *finditer(string) {
    const re = this._re("gd");
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(string)) !== null) {
      yield new PyMatch(m, this, string);
      if (m[0] === "") re.lastIndex += 1;
    }
  }

  /**
   * py: Pattern.sub
   * @param {string|((m: PyMatch) => string)} repl
   * @param {string} string
   * @param {number} [count] 0 means "all"
   */
  sub(repl, string, count = 0) {
    return this.subn(repl, string, count)[0];
  }

  /**
   * py: Pattern.subn
   * @param {string|((m: PyMatch) => string)} repl
   * @param {string} string
   * @param {number} [count]
   * @returns {[string, number]}
   */
  subn(repl, string, count = 0) {
    const tmpl =
      typeof repl === "string" ? pyReTemplate(repl, this.groups, this.groupindex) : null;
    const re = this._re("gd");
    re.lastIndex = 0;
    let out = "";
    let last = 0;
    let n = 0;
    let m;
    while ((m = re.exec(string)) !== null) {
      if (count !== 0 && n >= count) break;
      out += string.slice(last, m.index);
      out +=
        tmpl !== null
          ? tmpl.apply(m)
          : /** @type {(m: PyMatch) => string} */ (repl)(new PyMatch(m, this, string));
      last = m.index + m[0].length;
      n += 1;
      if (m[0] === "") re.lastIndex += 1;
    }
    out += string.slice(last);
    return [out, n];
  }

  /** py: Pattern.split */
  split(string, maxsplit = 0) {
    const re = this._re("gd");
    re.lastIndex = 0;
    const out = [];
    let last = 0;
    let n = 0;
    let m;
    while ((m = re.exec(string)) !== null) {
      if (maxsplit !== 0 && n >= maxsplit) break;
      if (m[0] === "" && m.index === last && m.index === 0) {
        re.lastIndex += 1;
        if (re.lastIndex > string.length) break;
        continue;
      }
      out.push(string.slice(last, m.index));
      for (let i = 1; i <= this.groups; i += 1) out.push(m[i] === undefined ? null : m[i]);
      last = m.index + m[0].length;
      n += 1;
      if (m[0] === "") re.lastIndex += 1;
    }
    out.push(string.slice(last));
    return out;
  }
}

/* ------------------------------------------------------------ module API */

/** @type {Map<string, PyPattern>} */
const _compileCache = new Map();

/**
 * py: `re.compile`
 * @param {string} pattern @param {number} [flags] @returns {PyPattern}
 */
export function compile(pattern, flags = 0) {
  const key = flags + " " + pattern;
  let p = _compileCache.get(key);
  if (p === undefined) {
    p = new PyPattern(pattern, flags);
    _compileCache.set(key, p);
  }
  return p;
}

/** py: `re.match` */
export function match(pattern, string, flags = 0) {
  return compile(pattern, flags).match(string);
}
/** py: `re.fullmatch` */
export function fullmatch(pattern, string, flags = 0) {
  return compile(pattern, flags).fullmatch(string);
}
/** py: `re.search` */
export function search(pattern, string, flags = 0) {
  return compile(pattern, flags).search(string);
}
/** py: `re.findall` */
export function findall(pattern, string, flags = 0) {
  return compile(pattern, flags).findall(string);
}
/** py: `re.sub` */
export function sub(pattern, repl, string, count = 0, flags = 0) {
  return compile(pattern, flags).sub(repl, string, count);
}
/** py: `re.subn` */
export function subn(pattern, repl, string, count = 0, flags = 0) {
  return compile(pattern, flags).subn(repl, string, count);
}
/** py: `re.split` */
export function split(pattern, string, maxsplit = 0, flags = 0) {
  return compile(pattern, flags).split(string, maxsplit);
}
/** py: `re.escape` */
export const escape = pyReEscape;
