#!/usr/bin/env python3
"""Snapshot the Dialect attributes the PARSER reads, per dialect.

PORT_PLAN.md §7 P3, CONTRACTS.md §8.

  python3 tools/parser/extract_dialect_attrs.py   # writes corpus/parser/dialect_attrs.json

Why this file exists
--------------------
This is `tools/tokens/extract_settings.py`'s argument, one layer up. That file exists
because producing a token stream for dialect `d` needs `d`'s tokenizer settings, which
live in `sqlglot/dialects/<d>.py` — P5-P9 scope, not P1's. Rather than block P1 on P9 it
snapshots the *resolved* settings and drives `tokenizer_core.js` from them.

`Parser` has the same dependency and it had not been paid. `parse()` reads 35 attributes
off `self.dialect`, and the P3 AST probe was handing it an object literal carrying
whichever four had crashed loudly enough to get noticed. Everything else read back
`undefined`.

For the 24 base defaults that are falsy, `undefined` behaves like Python and the gap is
invisible. Eight are truthy, and there the parser silently took the opposite branch from
CPython on every row. `NULL_ORDERING` is the sharpest: the parser compares it against
the literals "nulls_are_small"/"nulls_are_last", so `undefined` fails a test CPython
passes. Those produce MISMATCHes rather than ERRORs, which is exactly why growing the
stand-in crash-by-crash never found them.

Base defaults alone are still not enough, because the AST oracle in `corpus/ast/` was
generated by CPython with each row's REAL dialect. Snowflake overrides three of the
eight (`SUPPORTS_USER_DEFINED_TYPES=False`, `NULL_ORDERING="nulls_are_large"`,
`ALTER_TABLE_ADD_REQUIRED_FOR_EACH_COLUMN=False`), so a base-dialect stand-in cannot
match a Snowflake oracle row no matter how faithful it is to the base class. Hence the
same fix P1 used: snapshot the resolved per-dialect values.

As with the tokenizer snapshot, when P5-P9 land the real dialect classes this file
becomes the assertion that their attribute derivations are right, rather than dead
scaffolding.
"""

import json
import os
import sys

REF = os.environ.get("SQLGLOT_REF", "/tmp/sqlglot-ref")
sys.path.insert(0, REF)

OUT = "corpus/parser/dialect_attrs.json"

# Every `self.dialect.<X>` the parser reads, derived mechanically from src/parser.js:
#
#   grep -oE "this\.dialect\.[A-Za-z_][A-Za-z0-9_]*" src/parser.js | sort -u
#
# Declared explicitly, in sorted order, for the same reason CORE_SLOTS is: an attribute
# that upstream adds (or that the JS port starts reading) shows up as a diff here
# instead of silently reading back `undefined` at runtime. `assert_covers` below fails
# the harvest if any name has gone away upstream.
PARSER_ATTRS = [
    "ALIAS_POST_TABLESAMPLE",
    "ALIAS_POST_VERSION",
    "ALTER_TABLE_ADD_REQUIRED_FOR_EACH_COLUMN",
    "ALTER_TABLE_SUPPORTS_CASCADE",
    "BYTE_STRING_IS_BYTES_TYPE",
    "CONCAT_COALESCE",
    "CREATABLE_KIND_MAPPING",
    "DPIPE_IS_STRING_CONCAT",
    "FORMAT_MAPPING",
    "HAS_DISTINCT_ARRAY_CONSTRUCTORS",
    "HEX_STRING_IS_INTEGER_TYPE",
    "IDENTIFIERS_CAN_START_WITH_DIGIT",
    "LEAST_GREATEST_IGNORES_NULLS",
    "NORMALIZE_NOT_NULL",
    "NULL_ORDERING",
    "NUMBERS_CAN_BE_UNDERSCORE_SEPARATED",
    "ON_CONDITION_EMPTY_BEFORE_ERROR",
    "PRESERVE_ORIGINAL_NAMES",
    "SAFE_DIVISION",
    "SET_OP_DISTINCT_BY_DEFAULT",
    "STRICT_STRING_CONCAT",
    "SUPPORTS_COLUMN_JOIN_MARKS",
    "SUPPORTS_FIXED_SIZE_ARRAYS",
    "SUPPORTS_LIMIT_ALL",
    "SUPPORTS_ORDER_BY_ALL",
    "SUPPORTS_USER_DEFINED_TYPES",
    "SUPPORTS_VALUES_DEFAULT",
    "TABLESAMPLE_SIZE_IS_PERCENT",
    "TIME_MAPPING",
    "TRY_CAST_REQUIRES_STRING",
    "TYPED_DIVISION",
    "UNESCAPED_SEQUENCES",
    "UNNEST_COLUMN_ONLY",
    "UUID_IS_STRING_TYPE",
    "VALID_INTERVAL_UNITS",
]

# Tries are nested dicts with an integer 0 end-marker; they need trie_to_json, not enc.
# (Same treatment, and same reason, as the keyword trie in extract_settings.py.)
TRIE_ATTRS = ["TIME_TRIE", "FORMAT_TRIE"]


def enc(v):
    """JSON-encode a Dialect attribute without losing anything observable.

    Same wire format as tools/tokens/extract_settings.py (`$s` set, `$d` dict) so the
    JS decoder is shared, plus `$c` for a class object. `SET_OP_DISTINCT_BY_DEFAULT` is
    keyed by `exp.Expr` SUBCLASS, not by string, so its keys have to survive the round
    trip as classes -- `{"$c": "Union"}` is looked up in the JS `exp` namespace.

    Sets are emitted sorted, as there: every set here (`VALID_INTERVAL_UNITS`) is a
    membership-test target, never iterated into output.
    """
    if v is None or isinstance(v, (bool, int, float, str)):
        return v
    if isinstance(v, type):
        return {"$c": v.__name__}
    if isinstance(v, (set, frozenset)):
        return {"$s": sorted((enc(x) for x in v), key=lambda z: json.dumps(z, sort_keys=True))}
    if isinstance(v, (list, tuple)):
        return [enc(x) for x in v]
    if isinstance(v, dict):
        # Insertion order preserved for the same reason as the tokenizer snapshot.
        return {"$d": [[enc(k), enc(val)] for k, val in v.items()]}
    raise TypeError(f"unencodable dialect attribute: {type(v)!r}")


def trie_to_json(node):
    """Nested trie dicts -> nested JSON, integer key 0 becoming "$end" (CONTRACTS §8)."""
    out = {}
    for k, v in node.items():
        if k == 0:
            out["$end"] = True
        else:
            out[k] = trie_to_json(v)
    return out


def assert_covers(Dialect):
    """Fail loudly if a declared attribute no longer exists upstream."""
    missing = [a for a in PARSER_ATTRS + TRIE_ATTRS if not hasattr(Dialect, a)]
    if missing:
        raise SystemExit(
            "these attributes are declared here but absent from upstream Dialect "
            f"(port drifted from the pinned ref): {', '.join(missing)}"
        )


def main():
    from sqlglot.dialects.dialect import Dialect

    assert_covers(Dialect)

    # Same enumeration as extract_settings.py: "" is the base dialect, and
    # `get_or_raise` resolves each name to the instance whose attributes are the
    # MRO-merged effective values -- which is the whole point of snapshotting rather
    # than reading the class bodies.
    dialects = {}
    for name in [""] + sorted(Dialect.classes):
        d = Dialect.get_or_raise(name)
        attrs = {a: enc(getattr(d, a)) for a in PARSER_ATTRS}
        for a in TRIE_ATTRS:
            attrs[a] = trie_to_json(getattr(d, a))
        dialects[name] = attrs

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump({"attrs": PARSER_ATTRS + TRIE_ATTRS, "dialects": dialects}, f,
                  indent=1, sort_keys=True)
        f.write("\n")
    print(f"{OUT}: {len(dialects)} dialects x {len(PARSER_ATTRS) + len(TRIE_ATTRS)} attributes")


if __name__ == "__main__":
    main()
