#!/usr/bin/env node
// py: sqlglot/expressions @ 91119bc
// Generate the declarative expression surface from the pinned parity oracles.
// The oracle is deliberately the input here: it was extracted by importing the
// pinned Python package, so it includes metaclass/trait inheritance results.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const exprs = JSON.parse(readFileSync("corpus/parity/exprs.json", "utf8"));
const funcs = JSON.parse(readFileSync("corpus/parity/functions.json", "utf8"));
mkdirSync("src/_gen", { recursive: true });
mkdirSync("src/expressions", { recursive: true });

const q = JSON.stringify;
const sqlNamesByClass = Object.fromEntries(funcs.sql_names);
const meta = [];
for (const [key, s] of Object.entries(exprs.classes)) {
  const traits = s.traits ?? s.bases.filter((x) => x !== "Expr" && x !== "Expression");
  const initOwner = s.init_owner ?? null;
  meta.push(`  ${q(key)}: Object.freeze({key:${q(key)},name:${q(s.name)},argTypes:Object.freeze(${q(s.arg_types)}),requiredArgs:Object.freeze(${q(s.required_args)}),traits:Object.freeze(${q(traits)}),bases:Object.freeze(${q(s.bases)}),initOwner:${q(initOwner)},isPrimitive:${s.is_primitive},hashRawArgs:${s.hash_raw_args},sqlNames:Object.freeze(${q(sqlNamesByClass[s.name] ?? [])})})`);
}
writeFileSync("src/_gen/expr_meta.js", `// Generated by tools/gen_expr_meta.mjs from sqlglot @ 91119bc. DO NOT EDIT.\nexport const EXPR_META = Object.freeze({\n${meta.join(",\n")}\n});\nexport const TRAITS = Object.freeze(Object.fromEntries(Object.entries(EXPR_META).map(([k,v]) => [k,v.traits])));\nexport const INIT_HOOKS = Object.freeze(Object.fromEntries(Object.entries(EXPR_META).filter(([,v]) => v.initOwner).map(([k,v]) => [k,v.initOwner])));\n`);

const classLines = Object.values(exprs.classes).map((s) =>
  `export const ${s.name} = defineExpr(EXPR_META[${q(s.name.toLowerCase())}]);`
);
writeFileSync("src/expressions/classes.js", `// Generated by tools/gen_expr_meta.mjs from sqlglot @ 91119bc. DO NOT EDIT.\nimport { defineExpr } from "./core.js";\nimport { EXPR_META } from "../_gen/expr_meta.js";\n${classLines.join("\n")}\n`);

const aliases = Object.fromEntries(funcs.function_by_name);
writeFileSync("src/_gen/function_meta.js", `// Generated by tools/gen_expr_meta.mjs from sqlglot @ 91119bc. DO NOT EDIT.\nexport const ALL_FUNCTION_NAMES = Object.freeze(${q(funcs.all_functions)});\nexport const FUNCTION_ALIASES = Object.freeze(${q(aliases)});\nexport const SQL_NAMES = Object.freeze(${q(Object.fromEntries(funcs.sql_names))});\n`);

writeFileSync("src/expressions/index.js", `// py: sqlglot/expressions/__init__.py @ 91119bc\nimport * as classes from "./classes.js";\nimport { registerExprClasses, registerInitHook } from "./core.js";\nimport { installQueryMethods } from "./query_methods.js";\nimport { installFocusedMethods, DType, PropertiesLocation } from "./focused_methods.js";\nimport { EXPR_META, TRAITS, INIT_HOOKS } from "../_gen/expr_meta.js";\nimport { ALL_FUNCTION_NAMES, FUNCTION_ALIASES } from "../_gen/function_meta.js";\nexport * from "./core.js";\nexport * from "./classes.js";\nexport { EXPR_META, TRAITS, INIT_HOOKS, DType, PropertiesLocation };\nexport const EXPR_CLASSES = Object.freeze(Object.fromEntries(Object.entries(EXPR_META).map(([key, meta]) => [key, classes[meta.name]])));\nregisterExprClasses(Object.fromEntries(Object.values(EXPR_META).flatMap((meta) => [[meta.name, classes[meta.name]], [meta.key, classes[meta.name]]])));\ninstallQueryMethods(classes);\ninstallFocusedMethods();\nconst UNIT_NAMES = Object.freeze({D:"DAY",H:"HOUR",M:"MINUTE",MS:"MILLISECOND",NS:"NANOSECOND",Q:"QUARTER",S:"SECOND",US:"MICROSECOND",W:"WEEK",Y:"YEAR"});\nfor (const meta of Object.values(EXPR_META)) if (meta.initOwner) registerInitHook(meta.name, (node, args) => { const unit = node.args.unit; if (!unit || !["Column","Literal","Var"].includes(unit.constructor?.name)) return; const name = String(unit.args.this ?? "").toUpperCase(); const normalized = UNIT_NAMES[name] || name; node.set("unit", meta.initOwner === "DateTrunc" ? new classes.Literal({this: normalized, is_string: true}) : new classes.Var({this: normalized})); });\nexport const ALL_FUNCTIONS = Object.freeze(ALL_FUNCTION_NAMES.map((name) => classes[name]));\nexport const FUNCTION_BY_NAME = Object.freeze(Object.fromEntries(Object.entries(FUNCTION_ALIASES).map(([name, className]) => [name, classes[className]])));\n`);
