// Generates src/_gen/unicode.js from the CPython full-range dump.
// PORT_PLAN.md §4.3 item 3 ("_gen/unicode.js — full-range isPrintable / isLowercase
// / isUppercase / isSpace tables") and §4.1 (_gen/ is generated, never hand-edited).
//
//   python3 spike/py/gen_unicode_ref.py > spike/out/unicode_ref.json
//   node tools/gen_unicode_tables.mjs
//
// Tables are delta-encoded base-36 so the generated file stays small; they decode
// into Int32Array at module init and are queried by binary search.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const ref = JSON.parse(readFileSync("spike/out/unicode_ref.json", "utf8"));

// [[s,e],...] -> "d0,d1,d2,..." base36 deltas over the flattened boundary list.
//
// Ends are stored EXCLUSIVE (e+1). With inclusive ends the parity test below is
// wrong exactly at each range's final code point (it lands on an odd index), which
// is one silent false-negative per range — e.g. 'z', 'Z', U+007E.
function encode(ranges) {
  const flat = [];
  for (const [a, b] of ranges) flat.push(a, b + 1);
  const deltas = [];
  let prev = 0;
  for (const v of flat) {
    deltas.push((v - prev).toString(36));
    prev = v;
  }
  return deltas.join(",");
}

const PREDS = [
  "isprintable",
  "islower",
  "isupper",
  "isspace",
  "istitlechar",
  // P1: the predicates tokenizer_core.js reaches (isalnum on every _advance(alnum),
  // isidentifier in _scan_number, isdigit on heredoc tags).
  "isalnum",
  "isidentifier",
  "isdigit",
];
const NAMES = {
  isprintable: "PRINTABLE",
  islower: "LOWERCASE",
  isupper: "UPPERCASE",
  isspace: "SPACE",
  istitlechar: "TITLECASE",
  isalnum: "ALNUM",
  isidentifier: "IDSTART",
  isdigit: "DIGIT",
};

let body = `// @generated by tools/gen_unicode_tables.mjs — DO NOT EDIT
//
// Source of truth: CPython ${ref.python_version} (unicodedata ${ref.unidata_version}),
// swept over 0..0x${ref.maxunicode.toString(16).toUpperCase()} (${(ref.maxunicode + 1).toLocaleString()} code points).
//
// These tables exist because runtime \\p{...} property escapes are bound to the
// *engine's* Unicode version, not the harvesting interpreter's. Node v22 ships
// Unicode 16.0 while the pinned toolchain runs unicodedata ${ref.unidata_version}; measured
// divergence between the two is 11,130 code points for isprintable alone
// (PORT_PLAN.md §4.6, §5.2, R6). Tables are exact by construction and move only
// when the corpus is re-harvested.
//
// Encoding: flattened [start, end] boundary pairs, delta-encoded base-36.

function decode(s) {
  const parts = s.split(",");
  const out = new Int32Array(parts.length);
  let prev = 0;
  for (let i = 0; i < parts.length; i++) {
    prev += parseInt(parts[i], 36);
    out[i] = prev;
  }
  return out;
}

// Boundaries are [start, endExclusive, start, endExclusive, ...], strictly
// increasing. cp is a member iff the index of the last boundary <= cp is even,
// i.e. we are between a start and its exclusive end.
function inRanges(table, cp) {
  let lo = 0;
  let hi = table.length - 1;
  if (cp < table[0]) return false;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (table[mid] <= cp) lo = mid + 1;
    else hi = mid - 1;
  }
  return (hi & 1) === 0;
}
`;

const counts = {};
for (const p of PREDS) {
  const enc = encode(ref.predicates[p]);
  counts[p] = { ranges: ref.predicates[p].length, bytes: enc.length };
  body += `\nconst ${NAMES[p]} = decode(\n  "${enc}",\n);\n`;
}

// Decimal digit runs: flat [start, end, valueAtStart] triples (not delta-encoded —
// there are only a few hundred and the value column breaks the monotonic delta trick).
if (ref.decimal_encoding_mismatches?.length) {
  throw new Error(
    `decimal run encoding is lossy on ${ref.decimal_encoding_mismatches.length} code points`,
  );
}
const decFlat = ref.decimal_runs.flat();
counts.decimal = { ranges: ref.decimal_runs.length, bytes: decFlat.join(",").length };
body += `\nconst DECIMAL_RUNS = new Int32Array([${decFlat.join(",")}]);\n`;

// str.upper(), as a code-point -> string map. Two parallel comma-joined lists: the
// code points delta-encoded base-36, and the replacement strings verbatim.
//
// Delegating to JS toUpperCase() here would be the same mistake as a runtime \p{...}:
// it is bound to the engine's Unicode version. Measured divergence Node v22 (Unicode
// 16.0) vs CPython 3.9.25 (unicodedata 13.0.0): 67 code points.
if (ref.upper_context_sensitive?.length) {
  throw new Error(
    "str.upper() is context-sensitive on " +
      `${JSON.stringify(ref.upper_context_sensitive)} — a per-code-point table cannot model it`,
  );
}
{
  const cps = [];
  const vals = [];
  let prev = 0;
  for (const [cp, s] of ref.upper_map) {
    if (s.includes(",")) throw new Error(`upper(${cp}) contains the list separator`);
    cps.push((cp - prev).toString(36));
    prev = cp;
    vals.push(s);
  }
  counts.upper = { ranges: ref.upper_map.length, bytes: cps.join(",").length + vals.join(",").length };
  body += `\nconst UPPER_CPS = decode(\n  "${cps.join(",")}",\n);\n`;
  body += `const UPPER_VALS = ${JSON.stringify(vals.join(","))}.split(",");\n`;
}

// str.lower(), same encoding as upper. NOT guarded by a `context_sensitive` throw the
// way upper is, because for lower that guard WOULD fire: U+03A3 lowercases to final
// sigma U+03C2 at end of word. The ref sweep reports the exact set, it is asserted to be
// that one code point, and `pyLower` refuses on it rather than emitting the wrong sigma.
{
  const sensitive = ref.lower_context_sensitive ?? [];
  if (sensitive.length !== 1 || sensitive[0] !== 0x3a3) {
    throw new Error(
      `str.lower() context-sensitivity changed: expected [0x3a3], got ` +
        JSON.stringify(sensitive.map((c) => `0x${c.toString(16)}`)),
    );
  }
  const cps = [];
  const vals = [];
  let prev = 0;
  for (const [cp, s] of ref.lower_map) {
    if (s.includes(",")) throw new Error(`lower(${cp}) contains the list separator`);
    cps.push((cp - prev).toString(36));
    prev = cp;
    vals.push(s);
  }
  counts.lower = { ranges: ref.lower_map.length, bytes: cps.join(",").length + vals.join(",").length };
  body += `\nconst LOWER_CPS = decode(\n  "${cps.join(",")}",\n);\n`;
  body += `const LOWER_VALS = ${JSON.stringify(vals.join(","))}.split(",");\n`;
  body += `\n// py: the ONE code point where str.lower() is context-sensitive (final sigma).\nexport const LOWER_CONTEXT_SENSITIVE = 0x${sensitive[0].toString(16)};\n`;
}

body += `
// py: str.isprintable() — per code point.
export function isPrintable(cp) {
  return inRanges(PRINTABLE, cp);
}

// py: str.islower() — per code point.
export function isLowercase(cp) {
  return inRanges(LOWERCASE, cp);
}

// py: str.isupper() — per code point.
export function isUppercase(cp) {
  return inRanges(UPPERCASE, cp);
}

// py: str.isspace() — per code point.
export function isSpace(cp) {
  return inRanges(SPACE, cp);
}

// py: Py_UNICODE_ISTITLE — the CHARACTER property (General_Category == Lt).
// This is deliberately NOT str.istitle(): 'A'.istitle() is True (the string is
// titlecase-formatted) but 'A' is not a titlecase character. _py/str.js needs the
// character property to compute "cased" for isupper()/islower().
export function isTitlecase(cp) {
  return inRanges(TITLECASE, cp);
}

// py: unicodedata.decimal(ch) — decimal digit value, or -1 if not a decimal digit.
// Python's int()/float() accept any of these: int('٢٠٢٣') == 2023.
export function decimalValue(cp) {
  let lo = 0;
  let hi = DECIMAL_RUNS.length / 3 - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const s = DECIMAL_RUNS[mid * 3];
    const e = DECIMAL_RUNS[mid * 3 + 1];
    if (cp < s) hi = mid - 1;
    else if (cp > e) lo = mid + 1;
    else return DECIMAL_RUNS[mid * 3 + 2] + (cp - s);
  }
  return -1;
}

// py: str.isalnum() — per code point.
export function isAlnum(cp) {
  return inRanges(ALNUM, cp);
}

// py: str.isidentifier() on a SINGLE code point — Py_UNICODE_ISIDSTART, i.e.
// XID_Start plus '_'. tokenizer_core.py:970 only calls it on \`self._peek\`.
// The multi-character form (first char ID_Start, rest ID_Continue) is NOT modelled
// here because the tokenizer never needs it.
export function isIdentifierStart(cp) {
  return inRanges(IDSTART, cp);
}

// py: str.isdigit() — per code point. Wider than isDecimal: includes Numeric_Type=Digit
// (superscripts like U+00B2), narrower than isnumeric (excludes Nl/No fractions).
export function isDigit(cp) {
  return inRanges(DIGIT, cp);
}

// py: str.upper() for one code point. Returns the replacement string, which may be
// LONGER than one character ('ß' -> 'SS', 'ﬆ' -> 'ST'), or null when the mapping is
// the identity. Callers concatenate; str.upper() is not context-sensitive.
export function upperCodePoint(cp) {
  let lo = 0;
  let hi = UPPER_CPS.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const v = UPPER_CPS[mid];
    if (cp < v) hi = mid - 1;
    else if (cp > v) lo = mid + 1;
    else return UPPER_VALS[mid];
  }
  return null;
}

// py: str.lower() for one code point. Same shape as upperCodePoint, and the mapping is
// likewise 1-to-many in principle. UNLIKE upper, str.lower() is context-sensitive on
// exactly one code point — U+03A3, which becomes final sigma U+03C2 at end of word — so
// this function is NOT a complete model of str.lower() on its own; \`pyLower\` layers the
// refusal on top. See LOWER_CONTEXT_SENSITIVE.
export function lowerCodePoint(cp) {
  let lo = 0;
  let hi = LOWER_CPS.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const v = LOWER_CPS[mid];
    if (cp < v) hi = mid - 1;
    else if (cp > v) lo = mid + 1;
    else return LOWER_VALS[mid];
  }
  return null;
}

export const PROVENANCE = {
  python_version: ${JSON.stringify(ref.python_version)},
  unidata_version: ${JSON.stringify(ref.unidata_version)},
  maxunicode: ${ref.maxunicode},
};
`;

mkdirSync("src/_gen", { recursive: true });
writeFileSync("src/_gen/unicode.js", body);

console.log(`  wrote src/_gen/unicode.js  (${body.length.toLocaleString()} bytes)`);
for (const p of PREDS) {
  console.log(
    `    ${p.padEnd(13)} ${String(counts[p].ranges).padStart(5)} ranges, ` +
      `${counts[p].bytes.toLocaleString().padStart(8)} bytes encoded`,
  );
}
