// Generates src/_gen/unicode.js from the CPython full-range dump.
// PORT_PLAN.md §4.3 item 3 ("_gen/unicode.js — full-range isPrintable / isLowercase
// / isUppercase / isSpace tables") and §4.1 (_gen/ is generated, never hand-edited).
//
//   python3 spike/py/gen_unicode_ref.py > spike/out/unicode_ref.json
//   node tools/gen_unicode_tables.mjs
//
// Tables are delta-encoded base-36 so the generated file stays small; they decode
// into Int32Array at module init and are queried by binary search.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const ref = JSON.parse(readFileSync("spike/out/unicode_ref.json", "utf8"));

// [[s,e],...] -> "d0,d1,d2,..." base36 deltas over the flattened boundary list.
//
// Ends are stored EXCLUSIVE (e+1). With inclusive ends the parity test below is
// wrong exactly at each range's final code point (it lands on an odd index), which
// is one silent false-negative per range — e.g. 'z', 'Z', U+007E.
function encode(ranges) {
  const flat = [];
  for (const [a, b] of ranges) flat.push(a, b + 1);
  const deltas = [];
  let prev = 0;
  for (const v of flat) {
    deltas.push((v - prev).toString(36));
    prev = v;
  }
  return deltas.join(",");
}

const PREDS = ["isprintable", "islower", "isupper", "isspace", "istitlechar"];
const NAMES = {
  isprintable: "PRINTABLE",
  islower: "LOWERCASE",
  isupper: "UPPERCASE",
  isspace: "SPACE",
  istitlechar: "TITLECASE",
};

let body = `// @generated by tools/gen_unicode_tables.mjs — DO NOT EDIT
//
// Source of truth: CPython ${ref.python_version} (unicodedata ${ref.unidata_version}),
// swept over 0..0x${ref.maxunicode.toString(16).toUpperCase()} (${(ref.maxunicode + 1).toLocaleString()} code points).
//
// These tables exist because runtime \\p{...} property escapes are bound to the
// *engine's* Unicode version, not the harvesting interpreter's. Node v22 ships
// Unicode 16.0 while the pinned toolchain runs unicodedata ${ref.unidata_version}; measured
// divergence between the two is 11,130 code points for isprintable alone
// (PORT_PLAN.md §4.6, §5.2, R6). Tables are exact by construction and move only
// when the corpus is re-harvested.
//
// Encoding: flattened [start, end] boundary pairs, delta-encoded base-36.

function decode(s) {
  const parts = s.split(",");
  const out = new Int32Array(parts.length);
  let prev = 0;
  for (let i = 0; i < parts.length; i++) {
    prev += parseInt(parts[i], 36);
    out[i] = prev;
  }
  return out;
}

// Boundaries are [start, endExclusive, start, endExclusive, ...], strictly
// increasing. cp is a member iff the index of the last boundary <= cp is even,
// i.e. we are between a start and its exclusive end.
function inRanges(table, cp) {
  let lo = 0;
  let hi = table.length - 1;
  if (cp < table[0]) return false;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (table[mid] <= cp) lo = mid + 1;
    else hi = mid - 1;
  }
  return (hi & 1) === 0;
}
`;

const counts = {};
for (const p of PREDS) {
  const enc = encode(ref.predicates[p]);
  counts[p] = { ranges: ref.predicates[p].length, bytes: enc.length };
  body += `\nconst ${NAMES[p]} = decode(\n  "${enc}",\n);\n`;
}

body += `
// py: str.isprintable() — per code point.
export function isPrintable(cp) {
  return inRanges(PRINTABLE, cp);
}

// py: str.islower() — per code point.
export function isLowercase(cp) {
  return inRanges(LOWERCASE, cp);
}

// py: str.isupper() — per code point.
export function isUppercase(cp) {
  return inRanges(UPPERCASE, cp);
}

// py: str.isspace() — per code point.
export function isSpace(cp) {
  return inRanges(SPACE, cp);
}

// py: Py_UNICODE_ISTITLE — the CHARACTER property (General_Category == Lt).
// This is deliberately NOT str.istitle(): 'A'.istitle() is True (the string is
// titlecase-formatted) but 'A' is not a titlecase character. _py/str.js needs the
// character property to compute "cased" for isupper()/islower().
export function isTitlecase(cp) {
  return inRanges(TITLECASE, cp);
}

export const PROVENANCE = {
  python_version: ${JSON.stringify(ref.python_version)},
  unidata_version: ${JSON.stringify(ref.unidata_version)},
  maxunicode: ${ref.maxunicode},
};
`;

mkdirSync("src/_gen", { recursive: true });
writeFileSync("src/_gen/unicode.js", body);

console.log(`  wrote src/_gen/unicode.js  (${body.length.toLocaleString()} bytes)`);
for (const p of PREDS) {
  console.log(
    `    ${p.padEnd(13)} ${String(counts[p].ranges).padStart(5)} ranges, ` +
      `${counts[p].bytes.toLocaleString().padStart(8)} bytes encoded`,
  );
}
