// Extracts sqlglot/time.py's TIMEZONES set verbatim into src/_gen/timezones.js.
// Mechanical extraction, so the ~600 data lines are never hand-transcribed.
//
//   node tools/gen_timezones.mjs /tmp/sqlglot-ref

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const root = process.argv[2] ?? "/tmp/sqlglot-ref";
const src = readFileSync(`${root}/sqlglot/time.py`, "utf8");

// py: TIMEZONES: set[str] = { tz.lower() for tz in ( "...", ... ) }
const start = src.indexOf("TIMEZONES: set[str] = {");
if (start < 0) throw new Error("TIMEZONES block not found");
const block = src.slice(start);
// Anchor on the generator's own `for tz in (` — the first "(" in the block belongs
// to `tz.lower()`, whose empty parens would close immediately and yield nothing.
const forIn = block.indexOf("for tz in (");
if (forIn < 0) throw new Error("`for tz in (` not found in TIMEZONES block");
const open = block.indexOf("(", forIn);
let depth = 0;
let end = -1;
for (let i = open; i < block.length; i++) {
  if (block[i] === "(") depth++;
  else if (block[i] === ")") {
    depth--;
    if (depth === 0) {
      end = i;
      break;
    }
  }
}
if (end < 0) throw new Error("unterminated TIMEZONES tuple");

const names = [...block.slice(open, end).matchAll(/"([^"]*)"/g)].map((m) => m[1]);
if (names.length === 0) throw new Error("no timezone literals found");

// py: the comprehension lowercases every entry.
const lowered = names.map((n) => n.toLowerCase());
const unique = [...new Set(lowered)];

const body = `// @generated by tools/gen_timezones.mjs — DO NOT EDIT
// py: sqlglot/time.py TIMEZONES @ 91119bc
//
// Upstream builds this as {tz.lower() for tz in (...)}. Extraction is mechanical so
// the ${names.length} entries are never hand-transcribed; ${names.length - unique.length} collapse on lowercasing,
// exactly as the Python set comprehension does.

export const TIMEZONES = new Set([
${unique.map((n) => `  ${JSON.stringify(n)},`).join("\n")}
]);
`;

mkdirSync("src/_gen", { recursive: true });
writeFileSync("src/_gen/timezones.js", body);
console.log(
  `  wrote src/_gen/timezones.js — ${names.length} literals, ${unique.length} unique after .lower()`,
);
